{
  "name": "General Ledger",
  "compatibilityLevel": 1200,
  "model": {
    "culture": "nl-BE",
    "dataSources": [
      {
        "name": "sibgrpudmsqlsrvd0001",
        "connectionString": "Provider=SQLOLEDB.1;Persist Security Info=true;User ID=SibelcoAdmin;Initial Catalog=sibgrpudmdbd0002;Data Source=sibgrpudmsqlsrvd0001.database.windows.net",
        "impersonationMode": "impersonateServiceAccount",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Cost Center",
        "columns": [
          {
            "name": "DIM_CostCenter_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CostCenter_SKEY"
          },
          {
            "name": "Cost Center Code",
            "dataType": "string",
            "sourceColumn": "CostCenterCode"
          },
          {
            "name": "Cost Center Description",
            "dataType": "string",
            "sourceColumn": "CostCenterDescription"
          },
          {
            "name": "Cost Center Description English",
            "dataType": "string",
            "sourceColumn": "CostCenterDescriptionEnglish"
          },
          {
            "name": "Cost Center Type",
            "dataType": "string",
            "sourceColumn": "CostCenterType"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCostCenter",
            "source": {
              "query": "SELECT [dbo].[vDimCostCenter].[DIM_CostCenter_SKEY],[dbo].[vDimCostCenter].[CostCenterCode],[dbo].[vDimCostCenter].[CostCenterDescription],[dbo].[vDimCostCenter].[CostCenterDescriptionEnglish],[dbo].[vDimCostCenter].[CostCenterType],[dbo].[vDimCostCenter].[LegalEntityCode],[dbo].[vDimCostCenter].[LastUpdated],[dbo].[vDimCostCenter].[DIM_DataForest_SKEY] FROM [dbo].[vDimCostCenter] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCostCenter].[DIM_CostCenter_SKEY],[dbo].[vDimCostCenter].[CostCenterCode],[dbo].[vDimCostCenter].[CostCenterDescription],[dbo].[vDimCostCenter].[CostCenterDescriptionEnglish],[dbo].[vDimCostCenter].[CostCenterType],[dbo].[vDimCostCenter].[LegalEntityCode],[dbo].[vDimCostCenter].[LastUpdated],[dbo].[vDimCostCenter].[DIM_DataForest_SKEY] FROM [dbo].[vDimCostCenter] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCostCenter"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCostCenter].[DIM_CostCenter_SKEY],[dbo].[vDimCostCenter].[CostCenterCode],[dbo].[vDimCostCenter].[CostCenterDescription],[dbo].[vDimCostCenter].[CostCenterDescriptionEnglish],[dbo].[vDimCostCenter].[CostCenterType],[dbo].[vDimCostCenter].[LegalEntityCode],[dbo].[vDimCostCenter].[LastUpdated],[dbo].[vDimCostCenter].[DIM_DataForest_SKEY] FROM [dbo].[vDimCostCenter] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCostCenter].[DIM_CostCenter_SKEY],[dbo].[vDimCostCenter].[CostCenterCode],[dbo].[vDimCostCenter].[CostCenterDescription],[dbo].[vDimCostCenter].[CostCenterDescriptionEnglish],[dbo].[vDimCostCenter].[CostCenterType],[dbo].[vDimCostCenter].[LegalEntityCode],[dbo].[vDimCostCenter].[LastUpdated],[dbo].[vDimCostCenter].[DIM_DataForest_SKEY] FROM [dbo].[vDimCostCenter] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Accounting Currency",
        "columns": [
          {
            "name": "DIM_Currency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_SKEY"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Currency Description",
            "dataType": "string",
            "sourceColumn": "CurrencyDescription"
          },
          {
            "name": "ISO Code",
            "dataType": "string",
            "sourceColumn": "ISOCode"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "ISO Description",
            "dataType": "string",
            "sourceColumn": "ISODescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrency",
            "source": {
              "query": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCurrency"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Ledger Account",
        "columns": [
          {
            "name": "DIM_LedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LedgerAccount_SKEY"
          },
          {
            "name": "Ledger Account Number",
            "dataType": "string",
            "sourceColumn": "LedgerAccountNumber"
          },
          {
            "name": "Ledger Account Description",
            "dataType": "string",
            "sourceColumn": "LedgerAccountDescription"
          },
          {
            "name": "Ledger Account Description English",
            "dataType": "string",
            "sourceColumn": "LedgerAccountDescriptionEnglish"
          },
          {
            "name": "Ledger Account Type",
            "dataType": "string",
            "sourceColumn": "LedgerAccountType"
          },
          {
            "name": "Ledger Account Nature",
            "dataType": "string",
            "sourceColumn": "LedgerAccountNature"
          },
          {
            "name": "Ledger Account Group",
            "dataType": "string",
            "sourceColumn": "LedgerAccountGroup"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwDimLedgerAccount",
            "source": {
              "query": "SELECT [dbo].[vDimLedgerAccount].[DIM_LedgerAccount_SKEY],[dbo].[vDimLedgerAccount].[LedgerAccountNumber],[dbo].[vDimLedgerAccount].[LedgerAccountDescription],[dbo].[vDimLedgerAccount].[LedgerAccountDescriptionEnglish],[dbo].[vDimLedgerAccount].[LedgerAccountType],[dbo].[vDimLedgerAccount].[LedgerAccountNature],[dbo].[vDimLedgerAccount].[LedgerAccountGroup],[dbo].[vDimLedgerAccount].[LastUpdated],[dbo].[vDimLedgerAccount].[LegalEntityCode],[dbo].[vDimLedgerAccount].[DIM_DataForest_SKEY] FROM [dbo].[vDimLedgerAccount] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLedgerAccount].[DIM_LedgerAccount_SKEY],[dbo].[vDimLedgerAccount].[LedgerAccountNumber],[dbo].[vDimLedgerAccount].[LedgerAccountDescription],[dbo].[vDimLedgerAccount].[LedgerAccountDescriptionEnglish],[dbo].[vDimLedgerAccount].[LedgerAccountType],[dbo].[vDimLedgerAccount].[LedgerAccountNature],[dbo].[vDimLedgerAccount].[LedgerAccountGroup],[dbo].[vDimLedgerAccount].[LastUpdated],[dbo].[vDimLedgerAccount].[LegalEntityCode],[dbo].[vDimLedgerAccount].[DIM_DataForest_SKEY] FROM [dbo].[vDimLedgerAccount] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimLedgerAccount"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimLedgerAccount].[DIM_LedgerAccount_SKEY],[dbo].[vDimLedgerAccount].[LedgerAccountNumber],[dbo].[vDimLedgerAccount].[LedgerAccountDescription],[dbo].[vDimLedgerAccount].[LedgerAccountDescriptionEnglish],[dbo].[vDimLedgerAccount].[LedgerAccountType],[dbo].[vDimLedgerAccount].[LedgerAccountNature],[dbo].[vDimLedgerAccount].[LedgerAccountGroup],[dbo].[vDimLedgerAccount].[LastUpdated],[dbo].[vDimLedgerAccount].[LegalEntityCode],[dbo].[vDimLedgerAccount].[DIM_DataForest_SKEY] FROM [dbo].[vDimLedgerAccount] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLedgerAccount].[DIM_LedgerAccount_SKEY],[dbo].[vDimLedgerAccount].[LedgerAccountNumber],[dbo].[vDimLedgerAccount].[LedgerAccountDescription],[dbo].[vDimLedgerAccount].[LedgerAccountDescriptionEnglish],[dbo].[vDimLedgerAccount].[LedgerAccountType],[dbo].[vDimLedgerAccount].[LedgerAccountNature],[dbo].[vDimLedgerAccount].[LedgerAccountGroup],[dbo].[vDimLedgerAccount].[LastUpdated],[dbo].[vDimLedgerAccount].[LegalEntityCode],[dbo].[vDimLedgerAccount].[DIM_DataForest_SKEY] FROM [dbo].[vDimLedgerAccount] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Ledger Actuals",
        "columns": [
          {
            "name": "RecId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RecId"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "Period",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Period"
          },
          {
            "name": "DIM_Date_Transaction_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Transaction_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_BusinessUnit_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_BusinessUnit_SKEY"
          },
          {
            "name": "DIM_LedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LedgerAccount_SKEY"
          },
          {
            "name": "DIM_CostCenter_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CostCenter_SKEY"
          },
          {
            "name": "Transaction Serie",
            "dataType": "string",
            "sourceColumn": "TransactionNumberSequence",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Transaction Number",
            "dataType": "string",
            "sourceColumn": "TransactionNumber",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "ActualDebitAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualDebitAmountCurrAcc"
          },
          {
            "name": "ActualDebitAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualDebitAmountCurrReg"
          },
          {
            "name": "ActualCreditAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualCreditAmountCurrAcc"
          },
          {
            "name": "ActualCreditAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualCreditAmountCurrReg"
          },
          {
            "name": "ActualAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualAmountCurrAcc"
          },
          {
            "name": "ActualAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActualAmountCurrReg"
          },
          {
            "name": "DIM_GroupLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupCostCenter_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupCostCenter_SKEY"
          },
          {
            "name": "DIM_GroupLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLegalEntity_SKEY"
          },
          {
            "name": "DIM_GroupPlant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupPlant_SKEY"
          },
          {
            "name": "DIM_TgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLedgerAccount_SKEY"
          },
          {
            "name": "DIM_TgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "DIM_GroupTgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "Transaccion Objet Account",
            "dataType": "string",
            "sourceColumn": "TransaccionObjetAccount",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Transaccion Subsidiary Account",
            "dataType": "string",
            "sourceColumn": "TransaccionSubsidiaryAccount",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Transaction Explanation",
            "dataType": "string",
            "sourceColumn": "TransactionExplanation",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Transaction Explanation 2",
            "dataType": "string",
            "sourceColumn": "TransactionExplanation2",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "DIM_GroupTgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartment_SKEY"
          },
          {
            "name": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
          },
          {
            "name": "DIM_TgkPlant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkPlant_SKEY"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "Asset ID",
            "dataType": "string",
            "sourceColumn": "AssetID",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Brand Package Grade",
            "dataType": "string",
            "sourceColumn": "BrandPackageGrade",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Package Code",
            "dataType": "string",
            "sourceColumn": "PackageCode",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Project ID",
            "dataType": "string",
            "sourceColumn": "ProjectID",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "SIC Code",
            "dataType": "string",
            "sourceColumn": "SICCode",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Voucher Type",
            "dataType": "string",
            "sourceColumn": "VoucherType",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "Business Unit Code",
            "dataType": "string",
            "sourceColumn": "BusinessUnitCode",
            "displayFolder": "Ledger Actuals Meta"
          },
          {
            "name": "DIM_CounterParty_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_CounterParty_SKEY"
          },
          {
            "name": "DIM_TgkDepartment_Mapped_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_Mapped_SKEY"
          },
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY",
            "displayFolder": "Ledger Actuals Meta"
          }
        ],
        "partitions": [
          {
            "name": "vwFactLedgerActuals",
            "source": {
              "query": "SELECT [dbo].[vFactLedgerActuals].* FROM [dbo].[vFactLedgerActuals] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactLedgerActuals].* FROM [dbo].[vFactLedgerActuals] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Actual Debit Amount Curr Acc",
            "expression": "SUM([ActualDebitAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Accounting Currency"
          },
          {
            "name": "Actual Debit Amount Curr Reg",
            "expression": "SUM([ActualDebitAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Regional Currency"
          },
          {
            "name": "Actual Credit Amount Curr Acc",
            "expression": "SUM([ActualCreditAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Accounting Currency"
          },
          {
            "name": "Actual Credit Amount Curr Reg",
            "expression": "SUM([ActualCreditAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Regional Currency"
          },
          {
            "name": "Actual Amount Curr Acc",
            "expression": "SUM([ActualAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Accounting Currency"
          },
          {
            "name": "Actual Amount Curr Reg",
            "expression": "SUM([ActualAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Ledger Actuals Amount Regional Currency"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactLedgerActuals"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactLedgerActuals].* FROM [dbo].[vFactLedgerActuals] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactLedgerActuals].* FROM [dbo].[vFactLedgerActuals] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Ledger Period Balance",
        "columns": [
          {
            "name": "RecId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RecId"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY"
          },
          {
            "name": "DIM_Currency_Accounting_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Accounting_SKEY"
          },
          {
            "name": "DIM_Currency_Regional_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_Regional_SKEY"
          },
          {
            "name": "DIM_BusinessUnit_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_BusinessUnit_SKEY"
          },
          {
            "name": "DIM_LedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LedgerAccount_SKEY"
          },
          {
            "name": "DIM_CostCenter_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CostCenter_SKEY"
          },
          {
            "name": "DIM_GroupLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLegalEntity_SKEY"
          },
          {
            "name": "DIM_GroupPlant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupPlant_SKEY"
          },
          {
            "name": "DIM_GroupLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupCostCenter_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupCostCenter_SKEY"
          },
          {
            "name": "BalanceBeginAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceBeginAmountCurrAcc"
          },
          {
            "name": "BalanceBeginAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceBeginAmountCurrReg"
          },
          {
            "name": "BalanceDebitAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceDebitAmountCurrAcc"
          },
          {
            "name": "BalanceDebitAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceDebitAmountCurrReg"
          },
          {
            "name": "BalanceCreditAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceCreditAmountCurrAcc"
          },
          {
            "name": "BalanceCreditAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceCreditAmountCurrReg"
          },
          {
            "name": "BalanceAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceAmountCurrAcc"
          },
          {
            "name": "BalanceAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceAmountCurrReg"
          },
          {
            "name": "BalanceEndAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceEndAmountCurrAcc"
          },
          {
            "name": "BalanceEndAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BalanceEndAmountCurrReg"
          },
          {
            "name": "Ledger Version",
            "dataType": "string",
            "sourceColumn": "LedgerVersion",
            "displayFolder": "Ledger Period Balance Meta"
          },
          {
            "name": "DIM_GroupLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLedgerAccountHierarchy_SKEY"
          },
          {
            "name": "DIM_TgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupLegalEntity_Intercompany_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupLegalEntity_Intercompany_SKEY"
          },
          {
            "name": "DIM_TgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_SKEY"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "DIM_GroupTgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
          },
          {
            "name": "DIM_GroupTgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartment_SKEY"
          },
          {
            "name": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
          },
          {
            "name": "Book Account Type",
            "dataType": "string",
            "sourceColumn": "BookAccountType",
            "displayFolder": "Ledger Period Balance Meta"
          },
          {
            "name": "DIM_CounterParty_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CounterParty_SKEY"
          },
          {
            "name": "DIM_TgkPlant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkPlant_SKEY"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "Period",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Period",
            "displayFolder": "Ledger Period Balance Meta"
          },
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey"
          }
        ],
        "partitions": [
          {
            "name": "vwFactLedgerPeriodBalance",
            "source": {
              "query": "SELECT [dbo].[vFactLedgerPeriodBalance].[RecId],[dbo].[vFactLedgerPeriodBalance].[DIM_LegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Plant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Date_Period_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Accounting_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Regional_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_BusinessUnit_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_LedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_CostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_Intercompany_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupCostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[TgkLedgerAccountTgkDepartmentHashKey],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartmentHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[LedgerVersion],[dbo].[vFactLedgerPeriodBalance].[BookAccountType],[dbo].[vFactLedgerPeriodBalance].[Period],[dbo].[vFactLedgerPeriodBalance].[DIM_CounterParty_SKEY],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[DIM_DataForest_SKEY] FROM [dbo].[vFactLedgerPeriodBalance] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactLedgerPeriodBalance].[RecId],[dbo].[vFactLedgerPeriodBalance].[DIM_LegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Plant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Date_Period_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Accounting_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Regional_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_BusinessUnit_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_LedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_CostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_Intercompany_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupCostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[TgkLedgerAccountTgkDepartmentHashKey],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartmentHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[LedgerVersion],[dbo].[vFactLedgerPeriodBalance].[BookAccountType],[dbo].[vFactLedgerPeriodBalance].[Period],[dbo].[vFactLedgerPeriodBalance].[DIM_CounterParty_SKEY],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[DIM_DataForest_SKEY] FROM [dbo].[vFactLedgerPeriodBalance] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Balance Begin Amount Curr Acc",
            "expression": "SUM([BalanceBeginAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Accounting Currency"
          },
          {
            "name": "Balance Begin Amount Curr Reg",
            "expression": "SUM([BalanceBeginAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Regional Currency"
          },
          {
            "name": "Balance Debit Amount Curr Acc",
            "expression": "SUM([BalanceDebitAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Accounting Currency"
          },
          {
            "name": "Balance Debit Amount Curr Reg",
            "expression": "SUM([BalanceDebitAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Regional Currency"
          },
          {
            "name": "Balance Credit Amount Curr Acc",
            "expression": "SUM([BalanceCreditAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Accounting Currency"
          },
          {
            "name": "Balance Credit Amount Curr Reg",
            "expression": "SUM([BalanceCreditAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Regional Currency"
          },
          {
            "name": "Balance Amount Curr Acc",
            "expression": "SUM([BalanceAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Accounting Currency"
          },
          {
            "name": "ORG - Balance Amount Curr Reg",
            "expression": "SUM([BalanceAmountCurrReg])",
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "Balance End Amount Curr Acc",
            "expression": "SUM([BalanceEndAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Accounting Currency"
          },
          {
            "name": "Balance End Amount Curr Reg",
            "expression": "SUM([BalanceEndAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Regional Currency"
          },
          {
            "name": "Balance Amount Curr Reg",
            "expression": "SUM([BalanceAmountCurrReg])",
            "formatString": "#,0.00",
            "displayFolder": "Balance Amount Regional Currency"
          },
          {
            "name": "Previous Month - Balance End Amount Curr Reg",
            "expression": [
              "SUMX (",
              "    VALUES ( 'Date'[Year Month]),",
              "    IF (",
              "        CALCULATE ( COUNTROWS ( VALUES ( 'Date'[Date] ) ) )",
              "            = CALCULATE ( VALUES ( 'Date'[MonthDays]) ),",
              "        CALCULATE (",
              "            [Balance End Amount Curr Reg],",
              "            ALL ( 'Date' ),",
              "            FILTER (",
              "                ALL ( 'Date'[Year Month]),",
              "                'Date'[Year Month]",
              "                    = EARLIER ( 'Date'[Year Month] ) - 1",
              "            )",
              "        ),",
              "        CALCULATE (",
              "            [Balance End Amount Curr Reg],",
              "            ALL ( 'Date' ),",
              "            CALCULATETABLE ( VALUES ( 'Date'[DayInMonth] ) ),",
              "            FILTER (",
              "                ALL ( 'Date'[Year Month] ),",
              "                'Date'[Year Month]",
              "                    = EARLIER ( 'Date'[Year Month] ) - 1",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "isHidden": true
          },
          {
            "name": "FOCF",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"46999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI Cash Flow Accounting Currency"
          },
          {
            "name": "Net result - Share of the Group",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"39999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Trade Working Capital",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "31999_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"31999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "31999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"31999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32000_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32000\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32010_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32010\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32020_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32020\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32030_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32030\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32040_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32040\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32050_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32050\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32099_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32100_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32100\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32110_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32110\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32199_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32499_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32499\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"32999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35199_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36099_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36099_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_COS",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_NREC",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_SGA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_SGA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_SGA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_SGA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "EBITDA",
            "expression": "[3FEBITDA]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Gross Margin",
            "expression": "[30999]+[31999_COS]+[32099_COS]+[32199_COS]+[32499_COS]+[33999_COS]+[34999_COS]+[35999_COS]+[36999_COS]+[36099_COS]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Trade Working Capital as % of revenues",
            "expression": "DIVIDE([Trade Working Capital],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "Effective tax rate",
            "expression": "DIVIDE(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"39499\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"39299\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "30999",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "Gross margin as % of revenues",
            "expression": "DIVIDE([Gross Margin],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "SG&A",
            "expression": "[33999_SGA]+[34999_SGA]+[35999_SGA]+[36999_SGA]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "EBIT",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Cost of Sales",
            "expression": "[31999_COS]+[32099_COS]+[32199_COS]+[32499_COS]+[33999_COS]+[34999_COS]+[35999_COS]+[36999_COS]+[36099_COS]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "ROCE",
            "expression": "DIVIDE(([EBIT]+[31999_NREC]+[32999_NREC]+[33999_NREC]+[34999_NREC]+[35999_COS]+[36099_NREC]+[36999_NREC]),CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/19999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Cash Flow Accounting Currency"
          },
          {
            "name": "DaysInPeriod",
            "expression": "SUMX(FILTER('Date', [Balance End Amount Curr Acc]<> 0),'Date'[MonthDays])",
            "isHidden": true
          },
          {
            "name": "Personnel costs/ton",
            "expression": "DIVIDE([33999_COS],(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Maintenance costs/ton",
            "expression": "DIVIDE([35199_COS],(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Fixed Costs/ton",
            "expression": "DIVIDE(([33999_COS]+[35199_COS]+[36999_COS]),(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "36099",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "Rolling Trade Working Capital as % of revenues",
            "expression": "DIVIDE(CALCULATE ( [Trade Working Capital],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "DPO",
            "expression": "iferror(if(isblank([NetTradePayables])=true,blank(),IF([NetTradePayables]>[DPODEN4M],([NetTradePayables]-[DPODEN4M])/([DPODEN5M]-[DPODEN4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([NetTradePayables]>[DPODEN3M],([NetTradePayables]-[DPODEN3M])/([DPODEN4M]-[DPODEN3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([NetTradePayables]>[DPODEN2M],([NetTradePayables]-[DPODEN2M])/([DPODEN3M]-[DPODEN2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([NetTradePayables]>[DPODEN],(([NetTradePayables]-[DPODEN])/(([DPODEN2M]-[DPODEN]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([NetTradePayables]/[DPODEN]*[AllDaysInPeriod]))),blank())",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "DSO",
            "expression": "if(isblank([TradeReceivables])=true,blank(),IF([TradeReceivables]>[Revenue4M],([TradeReceivables]-[Revenue4M])/([Revenue5M]-[Revenue4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([TradeReceivables]>[Revenue3M],([TradeReceivables]-[Revenue3M])/([Revenue4M]-[Revenue3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([TradeReceivables]>[Revenue2M],([TradeReceivables]-[Revenue2M])/([Revenue3M]-[Revenue2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([TradeReceivables]>[Revenue],(([TradeReceivables]-[Revenue])/(([Revenue2M]-[Revenue]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([TradeReceivables]/[Revenue]*[AllDaysInPeriod])))",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "Rolling DSO",
            "expression": "DIVIDE(CALCULATE ( [DSO],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "Rolling DPO",
            "expression": "DIVIDE(CALCULATE ( [DPO],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "DIO",
            "expression": "iferror(if(isblank([Inventories])=true,blank(),IF([Inventories]>[DIODEN4M],([Inventories]-[DIODEN4M])/([DIODEN5M]-[DIODEN4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([Inventories]>[DIODEN3M],([Inventories]-[DIODEN3M])/([DIODEN4M]-[DIODEN3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([Inventories]>[DIODEN2M],([Inventories]-[DIODEN2M])/([DIODEN3M]-[DIODEN2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([Inventories]>[DIODEN],(([Inventories]-[DIODEN])/(([DIODEN2M]-[DIODEN]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([Inventories]/[DIODEN]*[AllDaysInPeriod]))),blank())",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "Rolling DIO",
            "expression": "DIVIDE(CALCULATE ( [DIO],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "DTWCO",
            "expression": "[DSO]+[DIO]+[DPO]",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Accounting Currency"
          },
          {
            "name": "Cash Conversion Rate",
            "expression": "DIVIDE(([Regional EBITDA]+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"50900\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"50910\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)),[Regional EBITDA])",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Maintenance Capex to Gross margin",
            "expression": "DIVIDE(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"50900\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0),[Gross Margin])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "EBITDA as % of revenues",
            "expression": "DIVIDE([EBITDA],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Receivables Overdue",
            "expression": "DIVIDE((CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"53000-D121\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"53000-D122\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"53000-D123\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"53000-D124\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"53000-D125\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)),CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10|15100\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Balance Accounting Currency"
          },
          {
            "name": "Write-Offs as a % of Revenue",
            "expression": "DIVIDE(CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35600\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Balance Accounting Currency"
          },
          {
            "name": "Variable Costs/ton",
            "expression": "DIVIDE(([32099_COS]+[32199_COS]+[32499_COS]+[34999_COS]+[31999_COS]+[36099]),(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Energy costs/ton",
            "expression": "DIVIDE(([34999_COS]),(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Packaging costs/ton",
            "expression": "DIVIDE(([32010_COS]+[32040_COS]),(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Raw material costs/ton",
            "expression": "DIVIDE(([32000_COS]+[32020_COS]+[32030_COS]+[32050_COS]+[32100_COS]+[32110_COS]),(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "MonthsInPeriod",
            "expression": "COUNTAX(FILTER('Date', [Balance End Amount Curr Acc]<> 0),'Date'[MonthDays])",
            "isHidden": true
          },
          {
            "name": "3F005R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F006R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F010R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F015R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F020R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F030R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F040R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F045R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F046R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F050R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F051R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F055R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F060R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F070R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F080R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F085R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F090R",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3SREG",
            "expression": "[3F005R]+[3F006R]+[3F010R]+[3F015R]+[3F020R]+[3F030R]+[3F040R]+[3F045R]+[3F046R]+[3F050R]+[3F051R]+[3F055R]+[3F060R]+[3F070R]+[3F080R]+[3F085R]+[3F090R]",
            "isHidden": true
          },
          {
            "name": "3F005G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F010G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F020G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F030G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F040G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F050G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F060G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F070G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F080G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F090G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F006G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F015G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F045G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F046G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F051G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F055G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F085G",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FGLO",
            "expression": "[3F005G]+[3F010G]+[3F020G]+[3F030G]+[3F040G]+[3F050G]+[3F060G]+[3F070G]+[3F080G]+[3F090G]+[3F006G]+[3F015G]+[3F045G]+[3F046G]+[3F051G]+[3F055G]+[3F085G]",
            "isHidden": true
          },
          {
            "name": "3FSGA",
            "expression": "[3SREG]+[3FGLO]",
            "isHidden": true
          },
          {
            "name": "3FCOS",
            "expression": "[31999_COS]+[32099_COS]+[32199_COS]+[32499_COS]+[33999_COS]+[34999_COS]+[35999_COS]+[36999_COS]+[36099_COS]",
            "isHidden": true
          },
          {
            "name": "3FGM",
            "expression": "[30999]+[3FCOS]",
            "isHidden": true
          },
          {
            "name": "3REGEBITDA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37699\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37808\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+[3SREG]+[3FGM]",
            "isHidden": true
          },
          {
            "name": "3FEBITDA",
            "expression": "[3REGEBITDA]+[3FGLO]",
            "isHidden": true
          },
          {
            "name": "Regional EBITDA",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37699\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"37808\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+[3SREG]+[Gross Margin]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "AllDaysInPeriod",
            "expression": "SUMX(FILTER('Date', [Balance End Amount Curr Acc]<> 0),'Date'[MonthDays])",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "TradeReceivables",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"15188\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "Revenue",
            "expression": "CALCULATE( sum([BalanceAmountCurrAcc]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "Previous Month - Revenue",
            "expression": "CALCULATE([Revenue],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "DSO1",
            "expression": "if(isblank([TradeReceivables])=true,blank(),IF([TradeReceivables]>[Revenue4M],([TradeReceivables]-[Revenue4M])/([Revenue5M]-[Revenue4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([TradeReceivables]>[Revenue3M],([TradeReceivables]-[Revenue3M])/([Revenue4M]-[Revenue3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([TradeReceivables]>[Revenue2M],([TradeReceivables]-[Revenue2M])/([Revenue3M]-[Revenue2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([TradeReceivables]>[Revenue],(([TradeReceivables]-[Revenue])/(([Revenue2M]-[Revenue]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([TradeReceivables]/[Revenue]*[AllDaysInPeriod])))",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "$ CM CY",
            "expression": "sum('Ledger Period Balance'[BalanceAmountCurrReg])",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$YTD CY",
            "expression": "sum('Ledger Period Balance'[BalanceEndAmountCurrReg])",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$ PM CY",
            "expression": "CALCULATE('Ledger Period Balance'[$ CM CY],PREVIOUSMONTH('Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$ CM PY",
            "expression": "CALCULATE('Ledger Period Balance'[$ CM CY],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$YTD PY",
            "expression": "CALCULATE('Ledger Period Balance'[$YTD CY],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$ CM-PM",
            "expression": "'Ledger Period Balance'[$ CM CY]-'Ledger Period Balance'[$ PM CY]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$ CM CY-PY",
            "expression": "'Ledger Period Balance'[$ CM CY]-'Ledger Period Balance'[$ CM PY]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$YTD CY-PY",
            "expression": "'Ledger Period Balance'[$YTD CY]-'Ledger Period Balance'[$YTD PY]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$% CM-PM",
            "expression": "IF(OR(ISBLANK([$ PM CY]) = true,round([$ PM CY],2)=0),BLANK(),DIVIDE([$ CM CY],'Ledger Period Balance'[$ PM CY])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$% CM CY-PY",
            "expression": "IF(OR(ISBLANK([$ CM PY]) = true,round([$ CM PY],2)=0),BLANK(),DIVIDE([$ CM CY],'Ledger Period Balance'[$ CM PY])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "$%YTD CY-PY",
            "expression": "IF(OR(ISBLANK([$YTD PY]) = true,round([$YTD PY],2)=0),BLANK(),DIVIDE([$YTD CY],'Ledger Period Balance'[$YTD PY])-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Time Intelligence - Balance Amount Regional Currency"
          },
          {
            "name": "FOCF Curr Reg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"46999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI Cash Flow Regional Currency"
          },
          {
            "name": "Net result - Share of the Group Curr Reg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"39999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "31999_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"31999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "31999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"31999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32000_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32000\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32010_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32010\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32020_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32020\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32030_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32030\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32040_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32040\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32050_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32050\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32099_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32100_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32100\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32110_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32110\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32199_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32499_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32499\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "32999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"32999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35199_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36099_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36099_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_COS_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"COS\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_NREC_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"NREC\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_SGA_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "34999_SGA_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "35999_SGA_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36999_SGA_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"SGA\",'Group Tgk Department Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "36099_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "30999_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F005R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F006R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F010R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F015R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F020R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F030R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F040R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F045R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F046R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F050R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F051R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F055R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F060R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F070R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F080R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F085R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F090R_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"REG090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3SREG_CurrReg",
            "expression": "[3F005R_CurrReg]+[3F006R_CurrReg]+[3F010R_CurrReg]+[3F015R_CurrReg]+[3F020R_CurrReg]+[3F030R_CurrReg]+[3F040R_CurrReg]+[3F045R_CurrReg]+[3F046R_CurrReg]+[3F050R_CurrReg]+[3F051R_CurrReg]+[3F055R_CurrReg]+[3F060R_CurrReg]+[3F070R_CurrReg]+[3F080R_CurrReg]+[3F085R_CurrReg]+[3F090R_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3F005G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO005\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F010G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO010\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F020G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO020\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F030G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO030\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F040G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO040\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F050G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO050\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F060G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO060\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F070G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO070\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F080G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO080\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F090G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO090\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F006G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO006\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F015G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO015\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F045G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO045\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F046G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO046\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F051G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO051\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F055G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO055\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3F085G_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"34999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"36999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0,SEARCH( \"GLO085\",'Tagetik Department'[Tagetik Department Code],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FGLO_CurrReg",
            "expression": "[3F005G_CurrReg]+[3F010G_CurrReg]+[3F020G_CurrReg]+[3F030G_CurrReg]+[3F040G_CurrReg]+[3F050G_CurrReg]+[3F060G_CurrReg]+[3F070G_CurrReg]+[3F080G_CurrReg]+[3F090G_CurrReg]+[3F006G_CurrReg]+[3F015G_CurrReg]+[3F045G_CurrReg]+[3F046G_CurrReg]+[3F051G_CurrReg]+[3F055G_CurrReg]+[3F085G_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3FSGA_CurrReg",
            "expression": "[3SREG_CurrReg]+[3FGLO_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3FCOS_CurrReg",
            "expression": "[31999_COS_CurrReg]+[32099_COS_CurrReg]+[32199_COS_CurrReg]+[32499_COS_CurrReg]+[33999_COS_CurrReg]+[34999_COS_CurrReg]+[35999_COS_CurrReg]+[36999_COS_CurrReg]+[36099_COS_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3FGM_CurrReg",
            "expression": "[30999_CurrReg]+[3FCOS_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3REGEBITDA_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37699\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37808\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+[3SREG_CurrReg]+[3FGM_CurrReg]",
            "isHidden": true
          },
          {
            "name": "3FEBITDA_CurrReg",
            "expression": "[3REGEBITDA_CurrReg]+[3FGLO_CurrReg]",
            "isHidden": true
          },
          {
            "name": "EBITDA Curr Reg",
            "expression": "[3FEBITDA_CurrReg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Regional EBITDA Curr Reg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37699\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37808\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+[3SREG_CurrReg]+[Gross Margin Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Trade Working Capital Curr Reg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Gross Margin Curr Reg",
            "expression": "[30999_CurrReg]+[31999_COS_CurrReg]+[32099_COS_CurrReg]+[32199_COS_CurrReg]+[32499_COS_CurrReg]+[33999_COS_CurrReg]+[34999_COS_CurrReg]+[35999_COS_CurrReg]+[36999_COS_CurrReg]+[36099_COS_CurrReg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Trade Working Capital as % of revenues Curr Reg",
            "expression": "DIVIDE([Trade Working Capital Curr Reg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Effective tax rate Curr Reg",
            "expression": "DIVIDE(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"39499\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"39299\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Gross margin as % of revenues Curr Reg",
            "expression": "DIVIDE([Gross Margin Curr Reg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "SG&A Curr Reg",
            "expression": "[33999_SGA_CurrReg]+[34999_SGA_CurrReg]+[35999_SGA_CurrReg]+[36999_SGA_CurrReg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "EBIT Curr Reg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"37999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Rolling Trade Working Capital as % of revenues Curr Reg",
            "expression": "DIVIDE(CALCULATE ( [Trade Working Capital Curr Reg],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Cost of Sales Curr Reg",
            "expression": "[31999_COS_CurrReg]+[32099_COS_CurrReg]+[32199_COS_CurrReg]+[32499_COS_CurrReg]+[33999_COS_CurrReg]+[34999_COS_CurrReg]+[35999_COS_CurrReg]+[36999_COS_CurrReg]+[36099_COS_CurrReg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "ROCE Curr Reg",
            "expression": "DIVIDE(([EBIT Curr Reg]+[31999_NREC_CurrReg]+[32999_NREC_CurrReg]+[33999_NREC_CurrReg]+[34999_NREC_CurrReg]+[35999_COS_CurrReg]+[36099_NREC_CurrReg]+[36999_NREC_CurrReg]),CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/19999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Cash Flow Regional Currency"
          },
          {
            "name": "DSO Curr Reg",
            "expression": "if(isblank([TradeReceivables_CurrReg])=true,blank(),IF([TradeReceivables_CurrReg]>[Revenue4M_CurrReg],([TradeReceivables_CurrReg]-[Revenue4M_CurrReg])/([Revenue5M_CurrReg]-[Revenue4M_CurrReg])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([TradeReceivables_CurrReg]>[Revenue3M_CurrReg],([TradeReceivables_CurrReg]-[Revenue3M_CurrReg])/([Revenue4M_CurrReg]-[Revenue3M_CurrReg])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([TradeReceivables_CurrReg]>[Revenue2M_CurrReg],([TradeReceivables_CurrReg]-[Revenue2M_CurrReg])/([Revenue3M_CurrReg]-[Revenue2M_CurrReg])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([TradeReceivables_CurrReg]>[Revenue_CurrReg],(([TradeReceivables_CurrReg]-[Revenue_CurrReg])/(([Revenue2M_CurrReg]-[Revenue_CurrReg]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([TradeReceivables_CurrReg]/[Revenue_CurrReg]*[AllDaysInPeriod])))",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Rolling DSO Curr Reg",
            "expression": "DIVIDE(CALCULATE ( [DSO Curr Reg],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "DPO Curr Reg",
            "expression": "iferror(if(isblank([NetTradePayables_CurrReg])=true,blank(),IF([NetTradePayables_CurrReg]>[DPODEN4M_CurrReg],([NetTradePayables_CurrReg]-[DPODEN4M_CurrReg])/([DPODEN5M_CurrReg]-[DPODEN4M_CurrReg])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([NetTradePayables_CurrReg]>[DPODEN3M_CurrReg],([NetTradePayables_CurrReg]-[DPODEN3M_CurrReg])/([DPODEN4M_CurrReg]-[DPODEN3M_CurrReg])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([NetTradePayables_CurrReg]>[DPODEN2M_CurrReg],([NetTradePayables_CurrReg]-[DPODEN2M_CurrReg])/([DPODEN3M_CurrReg]-[DPODEN2M_CurrReg])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([NetTradePayables_CurrReg]>[DPODEN_CurrReg],(([NetTradePayables_CurrReg]-[DPODEN_CurrReg])/(([DPODEN2M_CurrReg]-[DPODEN_CurrReg]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([NetTradePayables_CurrReg]/[DPODEN_CurrReg]*[AllDaysInPeriod]))),blank())",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Rolling DPO Curr Reg",
            "expression": "DIVIDE(CALCULATE ( [DPO Curr Reg],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "DIO Curr Reg",
            "expression": "iferror(if(isblank([Inventories_CurrReg])=true,blank(),IF([Inventories_CurrReg]>[DIODEN4M_CurrReg],([Inventories_CurrReg]-[DIODEN4M_CurrReg])/([DIODEN5M_CurrReg]-[DIODEN4M_CurrReg])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([Inventories_CurrReg]>[DIODEN3M_CurrReg],([Inventories_CurrReg]-[DIODEN3M_CurrReg])/([DIODEN4M_CurrReg]-[DIODEN3M_CurrReg])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([Inventories_CurrReg]>[DIODEN2M_CurrReg],([Inventories_CurrReg]-[DIODEN2M_CurrReg])/([DIODEN3M_CurrReg]-[DIODEN2M_CurrReg])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([Inventories_CurrReg]>[DIODEN_CurrReg],(([Inventories_CurrReg]-[DIODEN_CurrReg])/(([DIODEN2M_CurrReg]-[DIODEN_CurrReg]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([Inventories]/[DIODEN_CurrReg]*[AllDaysInPeriod]))),blank())",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Rolling DIO Curr Reg",
            "expression": "DIVIDE(CALCULATE ( [DIO Curr Reg],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( [MonthsInPeriod],    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "DTWCO Curr Reg",
            "expression": "[DSO Curr Reg]+[DIO Curr Reg]+[DPO Curr Reg]",
            "formatString": "#,0.00",
            "displayFolder": "KPI Working Capital Regional Currency"
          },
          {
            "name": "Cash Conversion Rate Curr Reg",
            "expression": "DIVIDE(([Regional EBITDA Curr Reg]+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"50900\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"50910\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)),[Regional EBITDA Curr Reg])",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Maintenance Capex to Gross margin Curr Reg",
            "expression": "DIVIDE(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"50900\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0),[Gross Margin Curr Reg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "EBITDA as % of revenues Curr Reg",
            "expression": "DIVIDE([EBITDA Curr Reg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Receivables Overdue Curr Reg",
            "expression": "DIVIDE((CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"53000-D121\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"53000-D122\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"53000-D123\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"53000-D124\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)+CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"53000-D125\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)),CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10|15100\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Balance Regional Currency"
          },
          {
            "name": "Write-Offs as a % of Revenue Curr Reg",
            "expression": "DIVIDE(CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"35600\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )),CALCULATE ( CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0),    DATESBETWEEN (        'Date'[Date],        NEXTDAY ( SAMEPERIODLASTYEAR (LASTDATE ( 'Date'[Date] ) ) ),        LASTDATE ( 'Date'[Date] )    )))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Balance Regional Currency"
          },
          {
            "name": "Variable Costs/ton Curr Reg",
            "expression": "DIVIDE(([32099_COS_CurrReg]+[32199_COS_CurrReg]+[32499_COS_CurrReg]+[34999_COS_CurrReg]+[31999_COS_CurrReg]+[36099_CurrReg]),(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Energy costs/ton Curr Reg",
            "expression": "DIVIDE(([34999_COS_CurrReg]),(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Packaging costs/ton Curr Reg",
            "expression": "DIVIDE(([32010_COS_CurrReg]+[32040_COS_CurrReg]),(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Raw material costs/ton Curr Reg",
            "expression": "DIVIDE(([32000_COS_CurrReg]+[32020_COS_CurrReg]+[32030_COS_CurrReg]+[32050_COS_CurrReg]+[32100_COS_CurrReg]+[32110_COS_CurrReg]),(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Fixed Costs/ton Curr Reg",
            "expression": "DIVIDE(([33999_COS_CurrReg]+[35199_COS_CurrReg]+[36999_COS_CurrReg]),(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Maintenance costs/ton Curr Reg",
            "expression": "DIVIDE([35199_COS_CurrReg],(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Personnel costs/ton Curr Reg",
            "expression": "DIVIDE([33999_COS_CurrReg],(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"52100\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)))",
            "formatString": "#,0.00",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "SG&A as % of revenues",
            "expression": "DIVIDE([SG&A],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "SG&A as % of revenues Curr Reg",
            "expression": "DIVIDE([SG&A Curr Reg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Regional SG&A as % of revenues",
            "expression": "DIVIDE([3SREG],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Regional SG&A as % of revenues Curr Reg",
            "expression": "DIVIDE([3SREG_CurrReg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Regional EBITDA as % of revenues",
            "expression": "DIVIDE([Regional EBITDA],[30999])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Accounting Currency"
          },
          {
            "name": "Regional EBITDA as % of revenues Curr Reg",
            "expression": "DIVIDE([Regional EBITDA Curr Reg],[30999_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "$ CM PY Regional SG&A as % of revenues Curr Reg",
            "expression": "CALCULATE([Regional SG&A as % of revenues Curr Reg],SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI P&L Regional Currency"
          },
          {
            "name": "Revenue2M",
            "expression": "[Revenue]+CALCULATE([Revenue],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "AllDaysInPeriod2M",
            "expression": "[AllDaysInPeriod]+CALCULATE([DaysInPeriod],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "Revenue3M",
            "expression": "[Revenue]+CALCULATE([Revenue2M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "AllDaysInPeriod3M",
            "expression": "[AllDaysInPeriod]+CALCULATE([AllDaysInPeriod2M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue4M",
            "expression": "[Revenue]+CALCULATE([Revenue3M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue5M",
            "expression": "[Revenue]+CALCULATE([Revenue4M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "AllDaysInPeriod4M",
            "expression": "[AllDaysInPeriod]+CALCULATE([AllDaysInPeriod3M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "AllDaysInPeriod5M",
            "expression": "[AllDaysInPeriod]+CALCULATE([AllDaysInPeriod4M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue_CurrReg",
            "expression": "CALCULATE( sum([BalanceAmountCurrReg]),SEARCH( \"30999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "Revenue2M_CurrReg",
            "expression": "[Revenue_CurrReg]+CALCULATE([Revenue_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue3M_CurrReg",
            "expression": "[Revenue_CurrReg]+CALCULATE([Revenue2M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue4M_CurrReg",
            "expression": "[Revenue_CurrReg]+CALCULATE([Revenue3M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Revenue5M_CurrReg",
            "expression": "[Revenue_CurrReg]+CALCULATE([Revenue4M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "TradeReceivables_CurrReg",
            "expression": "CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15199\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"15188\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "NetTradePayables",
            "expression": "-(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"15508\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"15508P\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0))",
            "isHidden": true
          },
          {
            "name": "NetTradePayables_CurrReg",
            "expression": "-(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15599\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"15508\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0)-CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"15508P\",'Tagetik Ledger Account'[Tagetik Ledger Account Number],1,0 ) > 0))",
            "isHidden": true
          },
          {
            "name": "DPODEN",
            "expression": "-([3FSGA_Period]+[3FCOS_Period]-[33999_Period])",
            "isHidden": true
          },
          {
            "name": "DPODEN_CurrReg",
            "expression": "-([3FSGA_Period_CurrReg]+[3FCOS_Period_CurrReg]-[33999_Period_CurrReg])",
            "isHidden": true
          },
          {
            "name": "DPODEN2M",
            "expression": "[DPODEN]+CALCULATE([DPODEN],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN3M",
            "expression": "[DPODEN]+CALCULATE([DPODEN2M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN4M",
            "expression": "[DPODEN]+CALCULATE([DPODEN3M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN5M",
            "expression": "[DPODEN]+CALCULATE([DPODEN4M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN5M_CurrReg",
            "expression": "[DPODEN_CurrReg]+CALCULATE([DPODEN4M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN2M_CurrReg",
            "expression": "[DPODEN_CurrReg]+CALCULATE([DPODEN_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN3M_CurrReg",
            "expression": "[DPODEN_CurrReg]+CALCULATE([DPODEN2M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPODEN4M_CurrReg",
            "expression": "[DPODEN_CurrReg]+CALCULATE([DPODEN3M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DPO1",
            "description": "DSO Test",
            "expression": "iferror(if(isblank([NetTradePayables])=true,blank(),IF([NetTradePayables]>[DPODEN4M],([NetTradePayables]-[DPODEN4M])/([DPODEN5M]-[DPODEN4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([NetTradePayables]>[DPODEN3M],([NetTradePayables]-[DPODEN3M])/([DPODEN4M]-[DPODEN3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([NetTradePayables]>[DPODEN2M],([NetTradePayables]-[DPODEN2M])/([DPODEN3M]-[DPODEN2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([NetTradePayables]>[DPODEN],(([NetTradePayables]-[DPODEN])/(([DPODEN2M]-[DPODEN]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([NetTradePayables]/[DPODEN]*[AllDaysInPeriod]))),blank())",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          },
          {
            "name": "3FCOS_Period",
            "expression": "CALCULATE( sum([BalanceAmountCurrAcc]),SEARCH( \"3FCOS\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FSGA_Period",
            "expression": "CALCULATE( sum([BalanceAmountCurrAcc]),SEARCH( \"3FSGA\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_Period",
            "expression": "CALCULATE( sum([BalanceAmountCurrAcc]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "33999_Period_CurrReg",
            "expression": "CALCULATE( sum([BalanceAmountCurrReg]),SEARCH( \"33999\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FCOS_Period_CurrReg",
            "expression": "CALCULATE( sum([BalanceAmountCurrReg]),SEARCH( \"3FCOS\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FSGA_Period_CurrReg",
            "expression": "CALCULATE( sum([BalanceAmountCurrReg]),SEARCH( \"3FSGA\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "Inventories",
            "expression": "(CALCULATE( sum([BalanceEndAmountCurrAcc]),SEARCH( \"10/15099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "isHidden": true
          },
          {
            "name": "Inventories_CurrReg",
            "expression": "(CALCULATE( sum([BalanceEndAmountCurrReg]),SEARCH( \"10/15099\",'Group Tgk Ledger Account Hierarchy'[PathNumber],1,0 ) > 0))",
            "isHidden": true
          },
          {
            "name": "DIODEN",
            "expression": "-([3FCOS_Period]+[3FDAS_Period])",
            "isHidden": true
          },
          {
            "name": "3FDAS_Period",
            "expression": "CALCULATE( sum([BalanceAmountCurrAcc]),SEARCH( \"3FDAS\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3FDAS_Period_CurrReg",
            "expression": "CALCULATE( sum([BalanceAmountCurrReg]),SEARCH( \"3FDAS\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "DIODEN2M",
            "expression": "[DIODEN]+CALCULATE([DIODEN],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN3M",
            "expression": "[DIODEN]+CALCULATE([DIODEN2M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN4M",
            "expression": "[DIODEN]+CALCULATE([DIODEN3M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN5M",
            "expression": "[DIODEN]+CALCULATE([DIODEN4M],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN_CurrReg",
            "expression": "-([3FCOS_Period_CurrReg]+[3FDAS_Period_CurrReg])",
            "isHidden": true
          },
          {
            "name": "DIODEN2M_CurrReg",
            "expression": "[DIODEN_CurrReg]+CALCULATE([DIODEN_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN3M_CurrReg",
            "expression": "[DIODEN_CurrReg]+CALCULATE([DIODEN2M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN4M_CurrReg",
            "expression": "[DIODEN_CurrReg]+CALCULATE([DIODEN3M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIODEN5M_CurrReg",
            "expression": "[DIODEN_CurrReg]+CALCULATE([DIODEN4M_CurrReg],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "DIO1",
            "expression": "iferror(if(isblank([Inventories])=true,blank(),IF([Inventories]>[DIODEN4M],([Inventories]-[DIODEN4M])/([DIODEN5M]-[DIODEN4M])*([AllDaysInPeriod5M]-[AllDaysInPeriod4M]),0)+IF([Inventories]>[DIODEN3M],([Inventories]-[DIODEN3M])/([DIODEN4M]-[DIODEN3M])*([AllDaysInPeriod4M]-[AllDaysInPeriod3M]),0)+IF([Inventories]>[DIODEN2M],([Inventories]-[DIODEN2M])/([DIODEN3M]-[DIODEN2M])*([AllDaysInPeriod3M]-[AllDaysInPeriod2M]),0)+IF([Inventories]>[DIODEN],(([Inventories]-[DIODEN])/(([DIODEN2M]-[DIODEN]))*([AllDaysInPeriod2M]-[AllDaysInPeriod]))+[AllDaysInPeriod],([Inventories]/[DIODEN]*[AllDaysInPeriod]))),blank())",
            "formatString": "0.00",
            "isHidden": true,
            "displayFolder": "Test DSO"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactLedgerPeriodBalance"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vFactLedgerPeriodBalance].[RecId],[dbo].[vFactLedgerPeriodBalance].[DIM_LegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Plant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Date_Period_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Accounting_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Regional_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_BusinessUnit_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_LedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_CostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_Intercompany_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupCostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[TgkLedgerAccountTgkDepartmentHashKey],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartmentHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[LedgerVersion],[dbo].[vFactLedgerPeriodBalance].[BookAccountType],[dbo].[vFactLedgerPeriodBalance].[Period],[dbo].[vFactLedgerPeriodBalance].[DIM_CounterParty_SKEY],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[DIM_DataForest_SKEY] FROM [dbo].[vFactLedgerPeriodBalance] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vFactLedgerPeriodBalance].[RecId],[dbo].[vFactLedgerPeriodBalance].[DIM_LegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Plant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Date_Period_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Accounting_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_Currency_Regional_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_BusinessUnit_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_LedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_CostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLegalEntity_Intercompany_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupCostCenter_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLegalEntity_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_TgkPlant_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccount_SKEY],[dbo].[vFactLedgerPeriodBalance].[TgkLedgerAccountTgkDepartmentHashKey],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkLedgerAccountHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartment_SKEY],[dbo].[vFactLedgerPeriodBalance].[DIM_GroupTgkDepartmentHierarchy_SKEY],[dbo].[vFactLedgerPeriodBalance].[LedgerVersion],[dbo].[vFactLedgerPeriodBalance].[BookAccountType],[dbo].[vFactLedgerPeriodBalance].[Period],[dbo].[vFactLedgerPeriodBalance].[DIM_CounterParty_SKEY],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrAcc],[dbo].[vFactLedgerPeriodBalance].[BalanceBeginAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceDebitAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceCreditAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[BalanceEndAmountCurrReg],[dbo].[vFactLedgerPeriodBalance].[DIM_DataForest_SKEY] FROM [dbo].[vFactLedgerPeriodBalance] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Legal Entity",
        "columns": [
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "Legal Entity Name",
            "dataType": "string",
            "sourceColumn": "LegalEntityName"
          },
          {
            "name": "Fiscal Code",
            "dataType": "string",
            "sourceColumn": "FiscalCode"
          },
          {
            "name": "Accounting Currency Code",
            "dataType": "string",
            "sourceColumn": "AccountingCurrencyCode"
          },
          {
            "name": "Regional Currency Code",
            "dataType": "string",
            "sourceColumn": "RegionalCurrencyCode"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "CountryCode"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "ZipCode"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Country Description",
            "dataType": "string",
            "sourceColumn": "CountryDescription"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Address 2",
            "dataType": "string",
            "sourceColumn": "Address2"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwDimLegalEntity",
            "source": {
              "query": "SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimLegalEntity"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimLegalEntity].[DIM_LegalEntity_SKEY],[dbo].[vDimLegalEntity].[LegalEntityCode],[dbo].[vDimLegalEntity].[LegalEntityName],[dbo].[vDimLegalEntity].[FiscalCode],[dbo].[vDimLegalEntity].[AccountingCurrencyCode],[dbo].[vDimLegalEntity].[RegionalCurrencyCode],[dbo].[vDimLegalEntity].[CountryCode],[dbo].[vDimLegalEntity].[CountryDescription],[dbo].[vDimLegalEntity].[StateCode],[dbo].[vDimLegalEntity].[ZipCode],[dbo].[vDimLegalEntity].[City],[dbo].[vDimLegalEntity].[Address],[dbo].[vDimLegalEntity].[Address2],[dbo].[vDimLegalEntity].[LastUpdated],[dbo].[vDimLegalEntity].[DIM_DataForest_SKEY] FROM [dbo].[vDimLegalEntity] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Plant",
        "columns": [
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY"
          },
          {
            "name": "Plant Code",
            "dataType": "string",
            "sourceColumn": "PlantCode"
          },
          {
            "name": "Plant Name",
            "dataType": "string",
            "sourceColumn": "PlantName"
          },
          {
            "name": "Plant Type",
            "dataType": "string",
            "sourceColumn": "PlantType"
          },
          {
            "name": "Fiscal Code",
            "dataType": "string",
            "sourceColumn": "FiscalCode"
          },
          {
            "name": "Country Code",
            "dataType": "string",
            "sourceColumn": "CountryCode"
          },
          {
            "name": "State Code",
            "dataType": "string",
            "sourceColumn": "StateCode"
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "ZipCode"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "Legal Entity Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LegalEntityCode"
          },
          {
            "name": "ShalePlayCode",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ShalePlayCode"
          },
          {
            "name": "DIM_ShalePlay_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_ShalePlay_SKEY"
          },
          {
            "name": "Last Updated",
            "dataType": "dateTime",
            "sourceColumn": "LastUpdated"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          }
        ],
        "partitions": [
          {
            "name": "vwDimPlant",
            "source": {
              "query": "SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimPlant"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimPlant].[DIM_Plant_SKEY],[dbo].[vDimPlant].[LegalEntityCode],[dbo].[vDimPlant].[PlantCode],[dbo].[vDimPlant].[PlantName],[dbo].[vDimPlant].[PlantType],[dbo].[vDimPlant].[FiscalCode],[dbo].[vDimPlant].[CountryCode],[dbo].[vDimPlant].[StateCode],[dbo].[vDimPlant].[ZipCode],[dbo].[vDimPlant].[City],[dbo].[vDimPlant].[Address],[dbo].[vDimPlant].[ShalePlayCode],[dbo].[vDimPlant].[DIM_ShalePlay_SKEY],[dbo].[vDimPlant].[LastUpdated],[dbo].[vDimPlant].[DIM_DataForest_SKEY] FROM [dbo].[vDimPlant] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Regional Currency",
        "columns": [
          {
            "name": "DIM_Currency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Currency_SKEY"
          },
          {
            "name": "Currency Code",
            "dataType": "string",
            "sourceColumn": "CurrencyCode"
          },
          {
            "name": "Currency Description",
            "dataType": "string",
            "sourceColumn": "CurrencyDescription"
          },
          {
            "name": "ISO Code",
            "dataType": "string",
            "sourceColumn": "ISOCode"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "ISO Description",
            "dataType": "string",
            "sourceColumn": "ISODescription"
          }
        ],
        "partitions": [
          {
            "name": "vwDimCurrency",
            "source": {
              "query": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCurrency"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCurrency].[DIM_Currency_SKEY],[dbo].[vDimCurrency].[CurrencyCode],[dbo].[vDimCurrency].[CurrencyDescription],[dbo].[vDimCurrency].[ISOCode],[dbo].[vDimCurrency].[ISODescription],[dbo].[vDimCurrency].[DIM_DataForest_SKEY] FROM [dbo].[vDimCurrency] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Tagetik Ledger Account",
        "columns": [
          {
            "name": "DIM_TgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLedgerAccount_SKEY"
          },
          {
            "name": "Tagetik Ledger Account Number",
            "dataType": "string",
            "sourceColumn": "TgkLedgerAccountNumber"
          },
          {
            "name": "Tagetik Ledger Account Description",
            "dataType": "string",
            "sourceColumn": "TgkLedgerAccountDescription"
          },
          {
            "name": "Tagetik Ledger Account Type",
            "dataType": "string",
            "sourceColumn": "TgkLedgerAccountType"
          },
          {
            "name": "Tagetik Ledger Account Category Id",
            "dataType": "string",
            "sourceColumn": "TgkLedgerAccountCategoryId",
            "sortByColumn": "SortingId"
          },
          {
            "name": "SortingId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SortingId"
          }
        ],
        "partitions": [
          {
            "name": "vwDimTgkLedgerAccount",
            "source": {
              "query": "SELECT [grp].[vDimTgkLedgerAccount].* FROM [grp].[vDimTgkLedgerAccount]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkLedgerAccount_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;174&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountNumber&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;156&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;172&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountType&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;143&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountCategoryId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;174&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SortingId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;74&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkLedgerAccount_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountNumber&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountDescription&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountType&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;3&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountCategoryId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;4&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SortingId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;5&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountType&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLedgerAccountCategoryId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;SortingId&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;boolean&gt;true&lt;/boolean&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnChecked&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimTgkLedgerAccount"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimTgkLedgerAccount].* FROM [grp].[vDimTgkLedgerAccount] "
          }
        ]
      },
      {
        "name": "Tagetik Department",
        "columns": [
          {
            "name": "DIM_TgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_SKEY"
          },
          {
            "name": "Tagetik Department Code",
            "dataType": "string",
            "sourceColumn": "TgkDepartmentCode"
          },
          {
            "name": "Tagetik Department Name",
            "dataType": "string",
            "sourceColumn": "TgkDepartmentName"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Department",
            "source": {
              "query": "SELECT [grp].[vDimTgkDepartment].* FROM [grp].[vDimTgkDepartment]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkDepartment_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;204&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkDepartmentCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;164&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkDepartmentName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;167&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkDepartment_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkDepartmentCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkDepartmentName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked /&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimTgkDepartment"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimTgkDepartment].* FROM [grp].[vDimTgkDepartment] "
          }
        ]
      },
      {
        "name": "Tagetik Legal Entity",
        "columns": [
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY"
          },
          {
            "name": "Tagetik Legal Entity Code",
            "dataType": "string",
            "sourceColumn": "TgkLegalEntityCode"
          },
          {
            "name": "Tagetik Legal Entity Name",
            "dataType": "string",
            "sourceColumn": "TgkLegalEntityName"
          }
        ],
        "partitions": [
          {
            "name": "vwDimTgkLegalEntity",
            "source": {
              "query": "SELECT [grp].[vDimTgkLegalEntity].* FROM [grp].[vDimTgkLegalEntity]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "&lt;?xml version=\"1.0\" encoding=\"UTF-16\"?&gt;&lt;Gemini xmlns=\"TableWidgetSerialization\"&gt;&lt;AnnotationContent&gt;&lt;![CDATA[&lt;?xml version=\"1.0\"?&gt;",
                  "&lt;TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"&gt;",
                  "  &lt;ColumnSuggestedType /&gt;",
                  "  &lt;ColumnFormat /&gt;",
                  "  &lt;ColumnAccuracy /&gt;",
                  "  &lt;ColumnCurrencySymbol /&gt;",
                  "  &lt;ColumnPositivePattern /&gt;",
                  "  &lt;ColumnNegativePattern /&gt;",
                  "  &lt;ColumnWidths&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkLegalEntity_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;197&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLegalEntityCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;157&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLegalEntityName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;160&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnWidths&gt;",
                  "  &lt;ColumnDisplayIndex&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;DIM_TgkLegalEntity_SKEY&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;0&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLegalEntityCode&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;1&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "    &lt;item&gt;",
                  "      &lt;key&gt;",
                  "        &lt;string&gt;TgkLegalEntityName&lt;/string&gt;",
                  "      &lt;/key&gt;",
                  "      &lt;value&gt;",
                  "        &lt;int&gt;2&lt;/int&gt;",
                  "      &lt;/value&gt;",
                  "    &lt;/item&gt;",
                  "  &lt;/ColumnDisplayIndex&gt;",
                  "  &lt;ColumnFrozen /&gt;",
                  "  &lt;ColumnChecked /&gt;",
                  "  &lt;ColumnFilter /&gt;",
                  "  &lt;SelectionFilter /&gt;",
                  "  &lt;FilterParameters /&gt;",
                  "  &lt;IsSortDescending&gt;false&lt;/IsSortDescending&gt;",
                  "&lt;/TableWidgetGridSerialization&gt;]]&gt;&lt;/AnnotationContent&gt;&lt;/Gemini&gt;"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimTgkLegalEntity"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimTgkLegalEntity].* FROM [grp].[vDimTgkLegalEntity] "
          }
        ]
      },
      {
        "name": "Group Tgk Ledger Account",
        "columns": [
          {
            "name": "DIM_GroupTgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccount_SKEY"
          },
          {
            "name": "Group Tgk Ledger Account Number",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountNumber"
          },
          {
            "name": "Group Tgk Ledger Account Description",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountDescription"
          },
          {
            "name": "Group Tgk Ledger Account Type",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountType"
          }
        ],
        "partitions": [
          {
            "name": "Group Tgk Ledger Account",
            "source": {
              "query": "SELECT [grp].[vDimGroupTgkLedgerAccount].* FROM [grp].[vDimGroupTgkLedgerAccount]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkLedgerAccount"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkLedgerAccount].* FROM [grp].[vDimGroupTgkLedgerAccount] "
          }
        ]
      },
      {
        "name": "Group Tgk Ledger Account Hierarchy",
        "columns": [
          {
            "name": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
          },
          {
            "name": "Group Tgk Ledger Account Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountNumber"
          },
          {
            "name": "Group Tgk Ledger Account Number Clean",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountNumberClean"
          },
          {
            "name": "Group Tgk Ledger Account Description",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountDescription"
          },
          {
            "name": "Group Tgk Ledger Account Parent HashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountParentHashKey"
          },
          {
            "name": "Group Tgk Ledger Account Parent Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountParentNumber"
          },
          {
            "name": "Group Tgk Ledger Account Parent Number Clean",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountParentNumberClean"
          },
          {
            "name": "Group Tgk Ledger Account Parent Description",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountParentDescription"
          },
          {
            "name": "Group Tgk Ledger Account Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountType"
          },
          {
            "type": "calculated",
            "name": "Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH([DIM_GroupTgkLedgerAccountHierarchy_SKEY],[Group Tgk Ledger Account Parent HashKey])"
          },
          {
            "type": "calculated",
            "name": "Level 1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account Description],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],1,0))"
          },
          {
            "type": "calculated",
            "name": "Level 2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],2,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],2,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 2 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 2 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],3,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],3,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 3 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 3 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],4,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],4,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 4 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 4 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 5",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],5,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],5,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 5 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 5 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 6",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],6,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],6,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 6 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 6 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 7",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],7,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],7,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 7 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 7 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 8",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],8,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],8,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 8 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 8 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 9",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],9,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],9,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 9 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 9 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 10",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],10,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],10,0))& \" (\" & IF( ISBLANK('Group Tgk Ledger Account Hierarchy'[Level 10 Count])=TRUE,0,'Group Tgk Ledger Account Hierarchy'[Level 10 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 11",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],11,0))"
          },
          {
            "type": "calculated",
            "name": "PathNumber",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account Number Clean],'Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account Parent Number Clean])"
          },
          {
            "name": "Group Tgk Ledger Account",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccount"
          },
          {
            "type": "calculated",
            "name": "Level2Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],2,0))"
          },
          {
            "type": "calculated",
            "name": "Level3Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],3,0))"
          },
          {
            "type": "calculated",
            "name": "Level 2 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level3Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level3Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level2Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level2Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level4Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],4,0))"
          },
          {
            "type": "calculated",
            "name": "Level5Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],5,0))"
          },
          {
            "type": "calculated",
            "name": "Level6Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],6,0))"
          },
          {
            "type": "calculated",
            "name": "Level7Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],7,0))"
          },
          {
            "type": "calculated",
            "name": "Level8Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],8,0))"
          },
          {
            "type": "calculated",
            "name": "Level9Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],9,0))"
          },
          {
            "type": "calculated",
            "name": "Level10Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],10,0))"
          },
          {
            "type": "calculated",
            "name": "Level11Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Ledger Account Hierarchy'[Group Tgk Ledger Account],'Group Tgk Ledger Account Hierarchy'[DIM_GroupTgkLedgerAccountHierarchy_SKEY],PATHITEM([PATH],11,0))"
          },
          {
            "type": "calculated",
            "name": "Level 3 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level4Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level4Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level3Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level3Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 4 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level5Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level5Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level4Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level4Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 5 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level6Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level6Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level5Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level5Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 6 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level7Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level7Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level6Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level6Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 7 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level8Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level8Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level7Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level7Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 8 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level9Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level9Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level8Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level8Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 9 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level10Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level10Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level9Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level9Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 10 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Ledger Account Hierarchy'[Level11Bis]),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level11Bis]<>\"\"),FILTER('Group Tgk Ledger Account Hierarchy','Group Tgk Ledger Account Hierarchy'[Level10Bis]=EARLIER('Group Tgk Ledger Account Hierarchy'[Level10Bis])))"
          }
        ],
        "partitions": [
          {
            "name": "Group Tgk Ledger Account Hierarchy",
            "source": {
              "query": " SELECT [grp].[vDimGroupTgkLedgerAccountHierarchy].* FROM [grp].[vDimGroupTgkLedgerAccountHierarchy] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>319</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>238</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountNumberClean</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>271</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>257</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>189</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>282</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>278</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentNumberClean</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>311</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>297</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountType</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>220</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountNumberClean</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccount</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentNumber</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentNumberClean</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountParentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountType</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccount</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "By Group Tgk Ledger Account Hierarchy",
            "levels": [
              {
                "name": "Level 1",
                "ordinal": 0,
                "column": "Level 1"
              },
              {
                "name": "Level 2",
                "ordinal": 1,
                "column": "Level 2"
              },
              {
                "name": "Level 3",
                "ordinal": 2,
                "column": "Level 3"
              },
              {
                "name": "Level 4",
                "ordinal": 3,
                "column": "Level 4"
              },
              {
                "name": "Level 5",
                "ordinal": 4,
                "column": "Level 5"
              },
              {
                "name": "Level 6",
                "ordinal": 5,
                "column": "Level 6"
              },
              {
                "name": "Level 7",
                "ordinal": 6,
                "column": "Level 7"
              },
              {
                "name": "Level 8",
                "ordinal": 7,
                "column": "Level 8"
              },
              {
                "name": "Level 9",
                "ordinal": 8,
                "column": "Level 9"
              },
              {
                "name": "Level 10",
                "ordinal": 9,
                "column": "Level 10"
              },
              {
                "name": "Level 11",
                "ordinal": 10,
                "column": "Level 11"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkLedgerAccountHierarchy"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkLedgerAccountHierarchy].* FROM [grp].[vDimGroupTgkLedgerAccountHierarchy] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>319</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>238</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountNumberClean</string>",
              "      </key>",
              "      <value>",
              "        <int>271</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>257</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccount</string>",
              "      </key>",
              "      <value>",
              "        <int>189</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>282</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>278</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentNumberClean</string>",
              "      </key>",
              "      <value>",
              "        <int>311</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>297</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountType</string>",
              "      </key>",
              "      <value>",
              "        <int>220</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountNumberClean</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccount</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentNumber</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentNumberClean</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountParentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountType</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccount</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Group Tgk Department",
        "columns": [
          {
            "name": "DIM_GroupDepartmentAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupDepartmentAccount_SKEY"
          },
          {
            "name": "Group Tgk Department Number",
            "dataType": "string",
            "sourceColumn": "GroupTgkDepartmentNumber"
          },
          {
            "name": "Group Tgk Department Description",
            "dataType": "string",
            "sourceColumn": "GroupTgkDepartmentDescription"
          }
        ],
        "partitions": [
          {
            "name": "Dim Group Tgk Department",
            "source": {
              "query": "SELECT [grp].[vDimGroupTgkDepartment].* FROM [grp].[vDimGroupTgkDepartment]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkDepartment"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkDepartment].* FROM [grp].[vDimGroupTgkDepartment] "
          }
        ]
      },
      {
        "name": "Group Tgk Department Hierarchy",
        "columns": [
          {
            "name": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
          },
          {
            "name": "GroupTgkDepartmentNumber",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentNumber"
          },
          {
            "name": "GroupTgkDepartmentNumberClean",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentNumberClean"
          },
          {
            "name": "GroupTgkDepartmentDescription",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentDescription"
          },
          {
            "name": "GroupTgkDepartmentParentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentParentHashKey"
          },
          {
            "name": "GroupTgkDepartmentParentNumber",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentParentNumber"
          },
          {
            "name": "GroupTgkDepartmentParentNumberClean",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentParentNumberClean"
          },
          {
            "name": "GroupTgkDepartmentParentDescription",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkDepartmentParentDescription"
          },
          {
            "type": "calculated",
            "name": "Path",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH('Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],'Group Tgk Department Hierarchy'[GroupTgkDepartmentParentHashKey])"
          },
          {
            "type": "calculated",
            "name": "Level 1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],1,0))"
          },
          {
            "type": "calculated",
            "name": "Level 2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],2,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],2,0))& \" (\" & IF( ISBLANK('Group Tgk Department Hierarchy'[Level 2 Count])=TRUE,0,'Group Tgk Department Hierarchy'[Level 2 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "IF(PATHITEM([PATH],3,0)=\"\",\"\",LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],3,0))& \" (\" & IF( ISBLANK('Group Tgk Department Hierarchy'[Level 3 Count])=TRUE,0,'Group Tgk Department Hierarchy'[Level 3 Count]) & \")\")"
          },
          {
            "type": "calculated",
            "name": "Level 4",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],4,0))"
          },
          {
            "type": "calculated",
            "name": "PathNumber",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "PATH('Group Tgk Department Hierarchy'[GroupTgkDepartmentNumberClean],'Group Tgk Department Hierarchy'[GroupTgkDepartmentParentNumberClean])"
          },
          {
            "type": "calculated",
            "name": "Level1Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],1,0))"
          },
          {
            "type": "calculated",
            "name": "Level2Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],2,0))"
          },
          {
            "type": "calculated",
            "name": "Level3Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],3,0))"
          },
          {
            "type": "calculated",
            "name": "Level4Bis",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "LOOKUPVALUE('Group Tgk Department Hierarchy'[GroupTgkDepartmentDescription],'Group Tgk Department Hierarchy'[DIM_GroupTgkDepartmentHierarchy_SKEY],PATHITEM([PATH],4,0))"
          },
          {
            "type": "calculated",
            "name": "Level 2 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Department Hierarchy'[Level3Bis]),FILTER('Group Tgk Department Hierarchy','Group Tgk Department Hierarchy'[Level3Bis]<>\"\"),FILTER('Group Tgk Department Hierarchy','Group Tgk Department Hierarchy'[Level2Bis]=EARLIER('Group Tgk Department Hierarchy'[Level2Bis])))"
          },
          {
            "type": "calculated",
            "name": "Level 3 Count",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(DISTINCTCOUNT('Group Tgk Department Hierarchy'[Level4Bis]),FILTER('Group Tgk Department Hierarchy','Group Tgk Department Hierarchy'[Level4Bis]<>\"\"),FILTER('Group Tgk Department Hierarchy','Group Tgk Department Hierarchy'[Level3Bis]=EARLIER('Group Tgk Department Hierarchy'[Level3Bis])))"
          }
        ],
        "partitions": [
          {
            "name": "Dim Group Tgk Department Hierarchy",
            "source": {
              "query": "SELECT [grp].[vDimGroupTgkDepartmentHierarchy].* FROM [grp].[vDimGroupTgkDepartmentHierarchy]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "By Tgk Department Hierarchy",
            "levels": [
              {
                "name": "Level 1",
                "ordinal": 0,
                "column": "Level 1"
              },
              {
                "name": "Level 2",
                "ordinal": 1,
                "column": "Level 2"
              },
              {
                "name": "Level 3",
                "ordinal": 2,
                "column": "Level 3"
              },
              {
                "name": "Level 4",
                "ordinal": 3,
                "column": "Level 4"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkDepartmentHierarchy"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkDepartmentHierarchy].* FROM [grp].[vDimGroupTgkDepartmentHierarchy] "
          }
        ]
      },
      {
        "name": "Tagetik Plant",
        "columns": [
          {
            "name": "DIM_TgkPlant_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkPlant_SKEY"
          },
          {
            "name": "Tagetik Plant Code",
            "dataType": "string",
            "sourceColumn": "TgkPlantCode"
          },
          {
            "name": "Tagetik Plant Name",
            "dataType": "string",
            "sourceColumn": "TgkPlantName"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Plant",
            "source": {
              "query": "SELECT [grp].[vDimTgkPlant].* FROM [grp].[vDimTgkPlant]",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimTgkPlant"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimTgkPlant].* FROM [grp].[vDimTgkPlant] "
          }
        ]
      },
      {
        "name": "Data Forest",
        "columns": [
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY"
          },
          {
            "name": "Region Id",
            "dataType": "string",
            "sourceColumn": "RegionId"
          },
          {
            "name": "Forest Number",
            "dataType": "string",
            "sourceColumn": "ForestNumber"
          },
          {
            "name": "Forest Name",
            "dataType": "string",
            "sourceColumn": "ForestName"
          },
          {
            "name": "Data Forest Id",
            "dataType": "string",
            "sourceColumn": "DataForestId"
          }
        ],
        "partitions": [
          {
            "name": "Data Forest",
            "source": {
              "query": "SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDataForest"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimDataForest].* FROM [dbo].[vDimDataForest] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Counter Party",
        "columns": [
          {
            "name": "DIM_CounterParty_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_CounterParty_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Counterparty Code",
            "dataType": "string",
            "sourceColumn": "CounterpartyCode",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Counterparty Name",
            "dataType": "string",
            "sourceColumn": "CounterpartyName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Last Updated",
            "dataType": "string",
            "sourceColumn": "LastUpdated",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CertificateId",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CertificateId",
            "sourceProviderType": "WChar"
          },
          {
            "name": "ADFSlice",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ADFSlice",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DataSystemId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DataSystemId",
            "sourceProviderType": "Integer"
          },
          {
            "name": "UpdateDate",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "UpdateDate",
            "sourceProviderType": "WChar"
          },
          {
            "name": "EffectiveDate",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "EffectiveDate",
            "sourceProviderType": "WChar"
          },
          {
            "name": "EndDate",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "EndDate",
            "sourceProviderType": "WChar"
          },
          {
            "name": "CurrentIndicator",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrentIndicator",
            "sourceProviderType": "UnsignedTinyInt"
          },
          {
            "name": "ExecutionId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ExecutionId",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_DataForest_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_DataForest_SKEY",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Counter Party",
            "dataView": "full",
            "source": {
              "query": "SELECT [dbo].[vDimCounterParty].* FROM [dbo].[vDimCounterParty] where DIM_DataForest_SKEY like '20%'",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCounterParty].* FROM [dbo].[vDimCounterParty] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT [dbo].[vDimCounterParty].* FROM [dbo].[vDimCounterParty] where DIM_DataForest_SKEY like '20%'"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimCounterParty"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "QueryEditorSerialization",
            "value": "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>SELECT [dbo].[vDimCounterParty].* FROM [dbo].[vDimCounterParty] where DIM_DataForest_SKEY like '20%'</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Year Month",
            "dataType": "int64",
            "sourceColumn": "YearMonth"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month"
          },
          {
            "name": "Month Short Name",
            "dataType": "string",
            "sourceColumn": "MonthShortName",
            "sortByColumn": "Month"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "MonthName",
            "sortByColumn": "Month"
          },
          {
            "name": "Day Month Year",
            "dataType": "string",
            "sourceColumn": "DayMonthYear",
            "sortByColumn": "YearMonthDay"
          },
          {
            "name": "YearMonthDay",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "YearMonthDay"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "MonthDays",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MonthDays"
          },
          {
            "name": "DayInMonth",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DayInMonth"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "QuarterShortName"
          }
        ],
        "partitions": [
          {
            "name": "vwDimDate",
            "source": {
              "query": " SELECT [iso].[vDimDate].[DIM_Date_SKEY],[iso].[vDimDate].[Date],[iso].[vDimDate].[Year],[iso].[vDimDate].[QuarterShortName],[iso].[vDimDate].[YearMonth],[iso].[vDimDate].[Month],[iso].[vDimDate].[MonthShortName],[iso].[vDimDate].[MonthName],[iso].[vDimDate].[YearMonthDay],[iso].[vDimDate].[DayInMonth],[iso].[vDimDate].[DayMonthYear],[iso].[vDimDate].[MonthDays] FROM [iso].[vDimDate] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsoDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>62</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>82</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterShortName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>151</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>117</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>101</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Month</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>74</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthShortName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>143</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>109</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonthDay</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>111</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>99</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>107</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>142</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayMonthYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>126</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayMonthYearName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>161</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>97</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>70</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthShortNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>170</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>105</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsoDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Year</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterShortName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Month</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthShortName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearMonthDay</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInMonth</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayMonthYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayMonthYearName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthShortNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthDays</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>IsoDateKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearQuarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Quarter</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterShortName</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>QuarterName</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayInWeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DayMonthYearName</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>YearWeek</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Week</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>WeekName</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthShortNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>MonthNameYear</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>false</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "By Year - Month",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month Short Name"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "iso"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDate"
          },
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [iso].[vDimDate].[DIM_Date_SKEY],[iso].[vDimDate].[Date],[iso].[vDimDate].[Year],[iso].[vDimDate].[QuarterShortName],[iso].[vDimDate].[YearMonth],[iso].[vDimDate].[Month],[iso].[vDimDate].[MonthShortName],[iso].[vDimDate].[MonthName],[iso].[vDimDate].[YearMonthDay],[iso].[vDimDate].[DayInMonth],[iso].[vDimDate].[DayMonthYear],[iso].[vDimDate].[MonthDays] FROM [iso].[vDimDate] "
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IsoDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Year</string>",
              "      </key>",
              "      <value>",
              "        <int>62</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarter</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Quarter</string>",
              "      </key>",
              "      <value>",
              "        <int>82</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterShortName</string>",
              "      </key>",
              "      <value>",
              "        <int>151</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterName</string>",
              "      </key>",
              "      <value>",
              "        <int>117</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>101</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Month</string>",
              "      </key>",
              "      <value>",
              "        <int>74</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthShortName</string>",
              "      </key>",
              "      <value>",
              "        <int>143</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthName</string>",
              "      </key>",
              "      <value>",
              "        <int>109</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonthDay</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>111</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>99</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>107</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeekName</string>",
              "      </key>",
              "      <value>",
              "        <int>142</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayMonthYear</string>",
              "      </key>",
              "      <value>",
              "        <int>126</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayMonthYearName</string>",
              "      </key>",
              "      <value>",
              "        <int>161</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>97</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Week</string>",
              "      </key>",
              "      <value>",
              "        <int>70</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekName</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthShortNameYear</string>",
              "      </key>",
              "      <value>",
              "        <int>170</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthNameYear</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDays</string>",
              "      </key>",
              "      <value>",
              "        <int>105</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>IsoDateKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Year</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarter</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Quarter</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterShortName</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterName</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Month</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthShortName</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthName</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearMonthDay</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInMonth</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeekName</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayMonthYear</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayMonthYearName</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearWeek</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Week</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekName</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthShortNameYear</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthNameYear</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthDays</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>IsoDateKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearQuarter</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Quarter</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterShortName</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>QuarterName</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeek</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayInWeekName</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DayMonthYearName</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>YearWeek</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Week</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>WeekName</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthShortNameYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>MonthNameYear</string>",
              "      </key>",
              "      <value>",
              "        <boolean>false</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Period",
        "columns": [
          {
            "name": "Period",
            "dataType": "int64",
            "sourceColumn": "Period",
            "sourceProviderType": "Integer"
          }
        ],
        "partitions": [
          {
            "name": "Period",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimPeriod].* FROM [dbo].[vDimPeriod] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimPeriod].* FROM [dbo].[vDimPeriod] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimPeriod"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tagetik Ledger Account Reporting",
        "columns": [
          {
            "name": "GroupTgkLedgerAccountHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "GroupTgkLedgerAccountHashKey",
            "sourceProviderType": "Char"
          },
          {
            "name": "Reporting Line Number",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountNumber",
            "sortByColumn": "OrderNumber",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Reporting Line Description",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountDescription",
            "sourceProviderType": "WChar"
          },
          {
            "name": "OrderNumber",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderNumber",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Report Group",
            "dataType": "string",
            "sourceColumn": "ReportGroup",
            "sortByColumn": "MinOrderNumber",
            "sourceProviderType": "WChar"
          },
          {
            "type": "calculated",
            "name": "MinOrderNumber",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "CALCULATE(MIN('Tagetik Ledger Account Reporting'[OrderNumber]),FILTER('Tagetik Ledger Account Reporting','Tagetik Ledger Account Reporting'[ReportGroup2]=EARLIER('Tagetik Ledger Account Reporting'[ReportGroup2])))"
          },
          {
            "name": "ReportGroup2",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReportGroup2",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Highlight",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Highlight",
            "sourceProviderType": "BigInt"
          },
          {
            "name": "Report Name",
            "dataType": "string",
            "sourceColumn": "ReportName",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Reporting Line",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccount",
            "sortByColumn": "OrderNumber",
            "sourceProviderType": "WChar"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Ledger Account Reporting N",
            "dataView": "full",
            "source": {
              "query": " SELECT [grp].[vDimGroupTgkLedgerAccountReporting].* FROM [grp].[vDimGroupTgkLedgerAccountReporting] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkLedgerAccountReporting].* FROM [grp].[vDimGroupTgkLedgerAccountReporting] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkLedgerAccountReporting"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          }
        ]
      },
      {
        "name": "Tagetik Ledger Budget",
        "columns": [
          {
            "name": "DIM_TgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLedgerAccount_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_TgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "Period",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Period",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "sourceProviderType": "WChar",
            "displayFolder": "Tagetik Ledger Budget Meta"
          },
          {
            "name": "Segment Description",
            "dataType": "string",
            "sourceColumn": "SegmentDescription",
            "sourceProviderType": "WChar",
            "displayFolder": "Tagetik Ledger Budget Meta"
          },
          {
            "name": "BudgetBalanceEndAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BudgetBalanceEndAmountCurrAcc",
            "sourceProviderType": "Double"
          },
          {
            "name": "BudgetBalanceEndAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BudgetBalanceEndAmountCurrTrans",
            "sourceProviderType": "Double"
          },
          {
            "name": "DIM_CostCenter_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_CostCenter_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_LedgerAccount_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_LedgerAccount_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_TgkPlant_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_TgkPlant_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_CounterParty_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_CounterParty_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_AccountingCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_AccountingCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_TransactionCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TransactionCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_RegionalCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_RegionalCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_GroupTgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccount_SKEY"
          },
          {
            "name": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
          },
          {
            "name": "DIM_GroupTgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartment_SKEY"
          },
          {
            "name": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
          },
          {
            "name": "BudgetBalanceAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BudgetBalanceAmountCurrAcc"
          },
          {
            "name": "BudgetBalanceAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "BudgetBalanceAmountCurrTrans"
          },
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Ledger Budgets",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vFactTgkLedgerBudgets].* FROM [dbo].[vFactTgkLedgerBudgets] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>223</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>204</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>182</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Segment</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SegmentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceEndAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>247</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceEndAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>259</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CostCenter_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>200</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkPlant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>160</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>174</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CounterParty_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>190</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>261</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>319</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>242</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>300</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_AccountingCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>233</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TransactionCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>235</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_RegionalCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>215</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>223</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>235</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>301</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Segment</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SegmentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceEndAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceEndAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CostCenter_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkPlant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CounterParty_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_AccountingCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TransactionCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_RegionalCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>24</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>BudgetBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Budget Balance End Amount Curr Acc",
            "expression": "SUM([BudgetBalanceEndAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Tagetik Ledger Budget Accounting Currency"
          },
          {
            "name": "Budget Balance End Amount Curr Trans",
            "expression": "SUM([BudgetBalanceEndAmountCurrTrans])",
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Tagetik"
          },
          {
            "name": "Budget Balance End Amount Curr Reg",
            "expression": "SUM([BudgetBalanceEndAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Tagetik Ledger Budget Regional Currency"
          },
          {
            "name": "Budget Balance Amount Curr Acc",
            "expression": "SUM([BudgetBalanceAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Tagetik Ledger Budget Accounting Currency"
          },
          {
            "name": "Sum of BudgetBalanceAmountCurrTrans",
            "expression": "SUM([BudgetBalanceAmountCurrTrans])",
            "isHidden": true
          },
          {
            "name": "Budget Balance Amount Curr Reg",
            "expression": "SUM([BudgetBalanceAmountCurrAcc])",
            "formatString": "#,0.00",
            "displayFolder": "Tagetik Ledger Budget Regional Currency"
          },
          {
            "name": "$ Budget CM CY",
            "expression": "sum('Tagetik Ledger Budget'[BudgetBalanceAmountCurrAcc])",
            "isHidden": true
          },
          {
            "name": "$ Budget YTD CY",
            "expression": "sum('Tagetik Ledger Budget'[BudgetBalanceEndAmountCurrAcc])",
            "isHidden": true
          },
          {
            "name": "$ Budget PM CY",
            "expression": "CALCULATE('Tagetik Ledger Budget'[$ Budget CM CY],PREVIOUSMONTH('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "$ Budget CM PY",
            "expression": "CALCULATE([$ Budget CM CY],SAMEPERIODLASTYEAR('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "$ Budget YTD PY",
            "expression": "CALCULATE([$ Budget YTD CY],SAMEPERIODLASTYEAR('Date'[Date]))",
            "isHidden": true
          },
          {
            "name": "Budget Regional SG&A as % of revenues",
            "expression": "DIVIDE([3SREG_Budget_CurrReg],[30999_Budget_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Budget"
          },
          {
            "name": "30999_Budget_CurrReg",
            "expression": "CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"30999\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3SREG_Budget_CurrReg",
            "expression": "CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F005R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F006R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F010R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F051R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F070R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F020R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F030R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F040R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F050R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([BudgetBalanceAmountCurrAcc]),SEARCH( \"3F060R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vFactTgkLedgerBudgets].* FROM [dbo].[vFactTgkLedgerBudgets] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactTgkLedgerBudgets"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>223</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>204</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Segment</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SegmentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceEndAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>247</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceEndAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>259</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CostCenter_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>200</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkPlant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>160</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>174</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CounterParty_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>190</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>261</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>319</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>242</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>300</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_AccountingCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>233</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TransactionCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>235</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_RegionalCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>215</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>223</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>235</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>301</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Segment</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SegmentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceEndAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceEndAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CostCenter_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkPlant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CounterParty_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_AccountingCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TransactionCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_RegionalCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>24</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>BudgetBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tagetik Ledger Forecast",
        "columns": [
          {
            "name": "DIM_TgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLedgerAccount_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_TgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TgkDepartment_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "Period",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Period",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Date_Period_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_Period_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "sourceProviderType": "WChar",
            "displayFolder": "Tagetik Ledger Forecast Meta"
          },
          {
            "name": "Segment Description",
            "dataType": "string",
            "sourceColumn": "SegmentDescription",
            "sourceProviderType": "WChar",
            "displayFolder": "Tagetik Ledger Forecast Meta"
          },
          {
            "name": "DIM_CostCenter_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_CostCenter_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_LedgerAccount_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_LedgerAccount_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_Plant_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_Plant_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_TgkPlant_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_TgkPlant_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_LegalEntity_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_LegalEntity_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_TgkLegalEntity_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_TgkLegalEntity_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_CounterParty_SKEY",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DIM_CounterParty_SKEY",
            "sourceProviderType": "Integer"
          },
          {
            "name": "DIM_GroupTgkLedgerAccount_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccount_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_GroupTgkDepartment_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartment_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_AccountingCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_AccountingCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_TransactionCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_TransactionCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "DIM_RegionalCurrency_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_RegionalCurrency_SKEY",
            "sourceProviderType": "Char"
          },
          {
            "name": "ForecastBalanceAmountCurrAcc",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ForecastBalanceAmountCurrAcc"
          },
          {
            "name": "ForecastBalanceAmountCurrTrans",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ForecastBalanceAmountCurrTrans"
          },
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey"
          },
          {
            "name": "ForecastBalanceAmountCurrReg",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ForecastBalanceAmountCurrReg"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Ledger Forecast",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vFactTgkLedgerForecast].* FROM [dbo].[vFactTgkLedgerForecast] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>223</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>204</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>73</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>182</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Segment</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>90</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SegmentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>158</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrReg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>233</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>231</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>243</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CostCenter_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>176</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>200</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>137</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkPlant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>160</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>174</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>197</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CounterParty_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>190</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>261</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>319</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>242</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>300</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_AccountingCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>233</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TransactionCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>235</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_RegionalCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>215</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>301</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Period</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_Period_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Segment</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>4</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SegmentDescription</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>5</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrReg</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>23</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>6</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>7</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CostCenter_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>8</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>9</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Plant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>10</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkPlant_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>11</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_LegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>12</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TgkLegalEntity_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>13</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_CounterParty_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>14</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>15</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>16</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartment_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>17</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>18</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_AccountingCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>19</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_TransactionCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>20</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_RegionalCurrency_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>21</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>22</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrAcc</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrTrans</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>ForecastBalanceAmountCurrReg</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Forecast Balance End Amount Curr Acc",
            "expression": "TOTALYTD('Tagetik Ledger Forecast'[Forecast Balance Amount Curr Acc],'Date'[Date])  ",
            "formatString": "#,0",
            "displayFolder": "Tagetik Ledger Forecast Accounting Currency"
          },
          {
            "name": "Forecast Balance End Amount Curr Reg",
            "expression": "TOTALYTD('Tagetik Ledger Forecast'[Forecast Balance Amount Curr Reg],'Date'[Date])  ",
            "formatString": "#,0",
            "displayFolder": "Tagetik Ledger Forecast Regional Currency"
          },
          {
            "name": "Forecast Balance Amount Curr Acc",
            "expression": "SUM([ForecastBalanceAmountCurrAcc])",
            "formatString": "#,0",
            "displayFolder": "Tagetik Ledger Forecast Accounting Currency"
          },
          {
            "name": "Forecast Balance Amount Curr Reg",
            "expression": "SUM([ForecastBalanceAmountCurrReg])",
            "formatString": "#,0",
            "displayFolder": "Tagetik Ledger Forecast Regional Currency"
          },
          {
            "name": "30999_Forecast_CurrReg",
            "expression": "CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"30999\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "3SREG_Forecast_CurrReg",
            "expression": "CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F005R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F006R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F010R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F051R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F070R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F020R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F030R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F040R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F050R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)+CALCULATE( sum([ForecastBalanceAmountCurrReg]),SEARCH( \"3F060R\",'Tagetik Ledger Account Reporting'[Reporting Line Number],1,0 ) > 0)",
            "isHidden": true
          },
          {
            "name": "Forecast Regional SG&A as % of revenues",
            "expression": "DIVIDE([3SREG_Forecast_CurrReg],[30999_Forecast_CurrReg])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI Forecast"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vFactTgkLedgerForecast].* FROM [dbo].[vFactTgkLedgerForecast] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vFactTgkLedgerForecast"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>223</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>204</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>73</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>182</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Segment</string>",
              "      </key>",
              "      <value>",
              "        <int>90</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SegmentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>158</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrReg</string>",
              "      </key>",
              "      <value>",
              "        <int>233</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>231</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>243</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CostCenter_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>176</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>200</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>137</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkPlant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>160</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>174</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>197</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CounterParty_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>190</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>261</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>319</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>242</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>300</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_AccountingCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>233</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TransactionCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>235</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_RegionalCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>215</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>301</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Period</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_Period_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Segment</string>",
              "      </key>",
              "      <value>",
              "        <int>4</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SegmentDescription</string>",
              "      </key>",
              "      <value>",
              "        <int>5</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrReg</string>",
              "      </key>",
              "      <value>",
              "        <int>23</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <int>6</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <int>7</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CostCenter_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>8</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>9</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Plant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>10</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkPlant_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>11</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_LegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>12</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TgkLegalEntity_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>13</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_CounterParty_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>14</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccount_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>15</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkLedgerAccountHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>16</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartment_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>17</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_GroupTgkDepartmentHierarchy_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>18</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_AccountingCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>19</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_TransactionCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>20</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_RegionalCurrency_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>21</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>22</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrAcc</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrTrans</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>ForecastBalanceAmountCurrReg</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Reporting Bridge",
        "isHidden": true,
        "columns": [
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey",
            "sourceProviderType": "Char"
          },
          {
            "name": "GroupTgkLedgerAccountHashKey",
            "dataType": "string",
            "sourceColumn": "GroupTgkLedgerAccountHashKey",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Reporting Bridge",
            "dataView": "full",
            "source": {
              "query": " SELECT [grp].[vDimGroupTgkLedgerAccountTgkDepartmentBridge].* FROM [grp].[vDimGroupTgkLedgerAccountTgkDepartmentBridge] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>301</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>242</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>GroupTgkLedgerAccountHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkLedgerAccountTgkDepartmentBridge].* FROM [grp].[vDimGroupTgkLedgerAccountTgkDepartmentBridge] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkLedgerAccountTgkDepartmentBridge"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>301</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>242</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>GroupTgkLedgerAccountHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Tagetik Ledger Account Department",
        "isHidden": true,
        "columns": [
          {
            "name": "TgkLedgerAccountTgkDepartmentHashKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TgkLedgerAccountTgkDepartmentHashKey",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Tagetik Ledger Account Department",
            "dataView": "full",
            "source": {
              "query": " SELECT [grp].[vDimGroupTgkLedgerAccountTgkDepartment].* FROM [grp].[vDimGroupTgkLedgerAccountTgkDepartment] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>301</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked />",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [grp].[vDimGroupTgkLedgerAccountTgkDepartment].* FROM [grp].[vDimGroupTgkLedgerAccountTgkDepartment] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimGroupTgkLedgerAccountTgkDepartment"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "grp"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>301</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>TgkLedgerAccountTgkDepartmentHashKey</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked />",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Date Range",
        "isHidden": true,
        "columns": [
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "Date Range",
            "dataType": "string",
            "sourceColumn": "DateRange",
            "sourceProviderType": "Char"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date"
          },
          {
            "name": "DateRangeLY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DateRangeLY"
          }
        ],
        "partitions": [
          {
            "name": "Date Range",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimDateRange].* FROM [dbo].[vDimDateRange] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRange</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>64</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRangeLY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>118</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRange</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRangeLY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>Date</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRangeLY</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimDateRange].* FROM [dbo].[vDimDateRange] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDateRange"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DateRange</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>64</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DateRangeLY</string>",
              "      </key>",
              "      <value>",
              "        <int>118</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DateRange</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DateRangeLY</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>Date</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DateRangeLY</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      },
      {
        "name": "Benchmark",
        "columns": [
          {
            "name": "Benchmark",
            "dataType": "string",
            "sourceColumn": "Benchmark",
            "sourceProviderType": "Char"
          }
        ],
        "partitions": [
          {
            "name": "Benchmark",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimBenchmark].* FROM [dbo].[vDimBenchmark] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            }
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimBenchmark].* FROM [dbo].[vDimBenchmark] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimBenchmark"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          }
        ]
      },
      {
        "name": "Date Range Bis",
        "columns": [
          {
            "name": "DateRange",
            "dataType": "string",
            "sourceColumn": "DateRange",
            "sourceProviderType": "Char"
          },
          {
            "name": "AxisValue",
            "dataType": "string",
            "sourceColumn": "AxisValue",
            "sortByColumn": "SortColumn",
            "sourceProviderType": "WChar"
          },
          {
            "name": "DIM_Date_SKEY",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DIM_Date_SKEY",
            "sourceProviderType": "WChar"
          },
          {
            "name": "SortColumn",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SortColumn"
          }
        ],
        "partitions": [
          {
            "name": "Date Range Bis",
            "dataView": "full",
            "source": {
              "query": " SELECT [dbo].[vDimDateRangeBis].* FROM [dbo].[vDimDateRangeBis] ",
              "dataSource": "sibgrpudmsqlsrvd0001"
            },
            "annotations": [
              {
                "name": "TableWidgetSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
                  "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
                  "  <ColumnSuggestedType />",
                  "  <ColumnFormat />",
                  "  <ColumnAccuracy />",
                  "  <ColumnCurrencySymbol />",
                  "  <ColumnPositivePattern />",
                  "  <ColumnNegativePattern />",
                  "  <ColumnWidths>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRange</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>103</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AxisValue</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>91</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortColumn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>108</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>136</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnWidths>",
                  "  <ColumnDisplayIndex>",
                  "    <item>",
                  "      <key>",
                  "        <string>DateRange</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>0</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>AxisValue</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>1</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortColumn</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>2</int>",
                  "      </value>",
                  "    </item>",
                  "    <item>",
                  "      <key>",
                  "        <string>DIM_Date_SKEY</string>",
                  "      </key>",
                  "      <value>",
                  "        <int>3</int>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnDisplayIndex>",
                  "  <ColumnFrozen />",
                  "  <ColumnChecked>",
                  "    <item>",
                  "      <key>",
                  "        <string>SortColumn</string>",
                  "      </key>",
                  "      <value>",
                  "        <boolean>true</boolean>",
                  "      </value>",
                  "    </item>",
                  "  </ColumnChecked>",
                  "  <ColumnFilter />",
                  "  <SelectionFilter />",
                  "  <FilterParameters />",
                  "  <IsSortDescending>false</IsSortDescending>",
                  "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": " SELECT [dbo].[vDimDateRangeBis].* FROM [dbo].[vDimDateRangeBis] "
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "vDimDateRangeBis"
          },
          {
            "name": "_TM_ExtProp_DbSchemaName",
            "value": "dbo"
          },
          {
            "name": "TableWidgetSerialization",
            "value": [
              "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"TableWidgetSerialization\"><AnnotationContent><![CDATA[<?xml version=\"1.0\"?>",
              "<TableWidgetGridSerialization xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">",
              "  <ColumnSuggestedType />",
              "  <ColumnFormat />",
              "  <ColumnAccuracy />",
              "  <ColumnCurrencySymbol />",
              "  <ColumnPositivePattern />",
              "  <ColumnNegativePattern />",
              "  <ColumnWidths>",
              "    <item>",
              "      <key>",
              "        <string>DateRange</string>",
              "      </key>",
              "      <value>",
              "        <int>103</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AxisValue</string>",
              "      </key>",
              "      <value>",
              "        <int>91</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SortColumn</string>",
              "      </key>",
              "      <value>",
              "        <int>108</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>136</int>",
              "      </value>",
              "    </item>",
              "  </ColumnWidths>",
              "  <ColumnDisplayIndex>",
              "    <item>",
              "      <key>",
              "        <string>DateRange</string>",
              "      </key>",
              "      <value>",
              "        <int>0</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>AxisValue</string>",
              "      </key>",
              "      <value>",
              "        <int>1</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>SortColumn</string>",
              "      </key>",
              "      <value>",
              "        <int>2</int>",
              "      </value>",
              "    </item>",
              "    <item>",
              "      <key>",
              "        <string>DIM_Date_SKEY</string>",
              "      </key>",
              "      <value>",
              "        <int>3</int>",
              "      </value>",
              "    </item>",
              "  </ColumnDisplayIndex>",
              "  <ColumnFrozen />",
              "  <ColumnChecked>",
              "    <item>",
              "      <key>",
              "        <string>SortColumn</string>",
              "      </key>",
              "      <value>",
              "        <boolean>true</boolean>",
              "      </value>",
              "    </item>",
              "  </ColumnChecked>",
              "  <ColumnFilter />",
              "  <SelectionFilter />",
              "  <FilterParameters />",
              "  <IsSortDescending>false</IsSortDescending>",
              "</TableWidgetGridSerialization>]]></AnnotationContent></Gemini>"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a9abc490-ea06-4ebd-b40a-bde8475bc392",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "add8bd28-4307-4fbe-a7fd-aa13dd834989",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "913577a0-f5fc-4f15-80f0-314edecddc89",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_LedgerAccount_SKEY",
        "toTable": "Ledger Account",
        "toColumn": "DIM_LedgerAccount_SKEY"
      },
      {
        "name": "6ea28a0e-2a81-4114-ab5f-d93e8c7ba9dd",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_CostCenter_SKEY",
        "toTable": "Cost Center",
        "toColumn": "DIM_CostCenter_SKEY"
      },
      {
        "name": "be2369c5-804e-44b4-bda4-d2f5fd430a1a",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "355a5574-4d28-4570-8a5e-d4caaec925de",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "4e0f346d-35b4-4310-a218-7bcefbee82f2",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_TgkLedgerAccount_SKEY",
        "toTable": "Tagetik Ledger Account",
        "toColumn": "DIM_TgkLedgerAccount_SKEY"
      },
      {
        "name": "c1a661a5-17eb-4fc9-b32b-71357ccceb40",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_TgkDepartment_SKEY",
        "toTable": "Tagetik Department",
        "toColumn": "DIM_TgkDepartment_SKEY"
      },
      {
        "name": "006b80d2-1885-42ed-8adc-6b546d6194eb",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "8b5c1924-374a-4cf5-9d8b-1666563597e4",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_GroupTgkLedgerAccount_SKEY",
        "toTable": "Group Tgk Ledger Account",
        "toColumn": "DIM_GroupTgkLedgerAccount_SKEY"
      },
      {
        "name": "576663d7-a188-4d9a-8779-9072a19901fe",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
        "toTable": "Group Tgk Ledger Account Hierarchy",
        "toColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
      },
      {
        "name": "09ed832a-23d3-4df7-83b3-3182149f0d39",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_GroupTgkDepartment_SKEY",
        "toTable": "Group Tgk Department",
        "toColumn": "DIM_GroupDepartmentAccount_SKEY"
      },
      {
        "name": "f29dedf7-f159-4d2d-b471-822dba471e3a",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY",
        "toTable": "Group Tgk Department Hierarchy",
        "toColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
      },
      {
        "name": "ee742f56-8040-4b6a-96ef-a3cb8fa3b731",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_TgkPlant_SKEY",
        "toTable": "Tagetik Plant",
        "toColumn": "DIM_TgkPlant_SKEY"
      },
      {
        "name": "eb7e8099-30b9-42c2-8671-184b8bbc05e5",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "89143214-c903-4ff2-a85f-7a973cf23e33",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_Date_Transaction_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "8a18e185-2e1a-4f5f-ad6f-87896e28a8b6",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_CostCenter_SKEY",
        "toTable": "Cost Center",
        "toColumn": "DIM_CostCenter_SKEY"
      },
      {
        "name": "ff4a4b34-6e2f-46ac-9d84-fd3f4ea151dd",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_Currency_Accounting_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "72e2a97e-d4d3-4203-91a9-d853bd600d05",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_Currency_Regional_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "d13aa9de-63c2-496e-8e08-ff3aa088a1e2",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_Date_Period_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "c78147f5-0f75-4e28-ace3-a4a87130b682",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_LedgerAccount_SKEY",
        "toTable": "Ledger Account",
        "toColumn": "DIM_LedgerAccount_SKEY"
      },
      {
        "name": "da8e0ab1-6d48-439e-8e13-0cd5bafd19be",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "112ba03e-1c23-4e24-be51-7a6d8e229821",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "c49f891d-f736-4d52-8710-0ce39f750b75",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_TgkLedgerAccount_SKEY",
        "toTable": "Tagetik Ledger Account",
        "toColumn": "DIM_TgkLedgerAccount_SKEY"
      },
      {
        "name": "bdc1e26f-2eec-45cc-96e4-e7afe8e74a8d",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_TgkDepartment_SKEY",
        "toTable": "Tagetik Department",
        "toColumn": "DIM_TgkDepartment_SKEY"
      },
      {
        "name": "f223d244-6f78-4129-b52b-ab972a374acb",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "56622916-e21f-410f-a235-33f45b0dadea",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY",
        "toTable": "Group Tgk Department Hierarchy",
        "toColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
      },
      {
        "name": "77341813-848a-43f0-8740-29a567c2dd71",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_GroupTgkDepartment_SKEY",
        "toTable": "Group Tgk Department",
        "toColumn": "DIM_GroupDepartmentAccount_SKEY"
      },
      {
        "name": "de4ce1f2-8e54-499a-ae79-b06f4ea44088",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
        "toTable": "Group Tgk Ledger Account Hierarchy",
        "toColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
      },
      {
        "name": "caf0e8e7-6a00-4934-adff-ad716063de4b",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_GroupTgkLedgerAccount_SKEY",
        "toTable": "Group Tgk Ledger Account",
        "toColumn": "DIM_GroupTgkLedgerAccount_SKEY"
      },
      {
        "name": "cca8aa78-9adf-4688-ba78-1b8a1b23143b",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_TgkPlant_SKEY",
        "toTable": "Tagetik Plant",
        "toColumn": "DIM_TgkPlant_SKEY"
      },
      {
        "name": "bb5a50b7-403f-4144-9a66-3418a9f4d2d0",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_DataForest_SKEY",
        "toTable": "Data Forest",
        "toColumn": "DIM_DataForest_SKEY"
      },
      {
        "name": "71b054de-8b4b-4a5f-9519-7eeb49e17b64",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "DIM_CounterParty_SKEY",
        "toTable": "Counter Party",
        "toColumn": "DIM_CounterParty_SKEY"
      },
      {
        "name": "3fc87c27-855e-49da-9085-4b90a7706cca",
        "fromTable": "Ledger Actuals",
        "fromColumn": "DIM_CounterParty_SKEY",
        "toTable": "Counter Party",
        "toColumn": "DIM_CounterParty_SKEY"
      },
      {
        "name": "76f356a5-fa30-4867-b663-9b21c1f45335",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "Period",
        "toTable": "Period",
        "toColumn": "Period"
      },
      {
        "name": "9c492d6c-536a-415b-a5ff-8354c942a2eb",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_TgkLedgerAccount_SKEY",
        "toTable": "Tagetik Ledger Account",
        "toColumn": "DIM_TgkLedgerAccount_SKEY"
      },
      {
        "name": "c051a8a5-06b9-4cb3-a8ed-3672b49f5c80",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_TgkDepartment_SKEY",
        "toTable": "Tagetik Department",
        "toColumn": "DIM_TgkDepartment_SKEY"
      },
      {
        "name": "9e713be2-0c28-4cf7-acfc-c2aaf2e9bb9e",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "Period",
        "toTable": "Period",
        "toColumn": "Period"
      },
      {
        "name": "a00c4e62-2ae0-40b5-87d9-91e222cd600e",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_Date_Period_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "22928f02-49b2-459f-949d-7c2dc4c97e40",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_CostCenter_SKEY",
        "toTable": "Cost Center",
        "toColumn": "DIM_CostCenter_SKEY"
      },
      {
        "name": "1c40a8c4-ae29-46ba-9aca-5a83dc9e6459",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_LedgerAccount_SKEY",
        "toTable": "Ledger Account",
        "toColumn": "DIM_LedgerAccount_SKEY"
      },
      {
        "name": "30c75061-b0ed-4584-854d-bb93188f6381",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "9307896b-91c0-42c8-82af-6e16f4e56975",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_TgkPlant_SKEY",
        "toTable": "Tagetik Plant",
        "toColumn": "DIM_TgkPlant_SKEY"
      },
      {
        "name": "e3ffc827-0377-4006-ba7e-4bcf9846b3f6",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "84e2737f-7ba8-4317-82b0-c9eabfcc5f34",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "d680ab8a-61c3-4347-a5ec-fb2cc6f5aa48",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_CounterParty_SKEY",
        "toTable": "Counter Party",
        "toColumn": "DIM_CounterParty_SKEY"
      },
      {
        "name": "05610f4e-2e27-4048-815d-bcfa04facb49",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_AccountingCurrency_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "15233aa9-1277-41ad-8239-007380c3afea",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_RegionalCurrency_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "e32d57d1-9848-4388-98d0-b523804ed821",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY",
        "toTable": "Group Tgk Department Hierarchy",
        "toColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
      },
      {
        "name": "c7e3390b-214c-4801-b9c4-04918abc0d44",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_GroupTgkDepartment_SKEY",
        "toTable": "Group Tgk Department",
        "toColumn": "DIM_GroupDepartmentAccount_SKEY"
      },
      {
        "name": "3ed1c367-11a1-461a-8d40-cdda9a6ac114",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
        "toTable": "Group Tgk Ledger Account Hierarchy",
        "toColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
      },
      {
        "name": "ed4b37bb-9a95-47c6-abe6-c7ead225fcb9",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "DIM_GroupTgkLedgerAccount_SKEY",
        "toTable": "Group Tgk Ledger Account",
        "toColumn": "DIM_GroupTgkLedgerAccount_SKEY"
      },
      {
        "name": "72df9318-ed94-4b2e-8b07-21a3e9909a11",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_TgkLedgerAccount_SKEY",
        "toTable": "Tagetik Ledger Account",
        "toColumn": "DIM_TgkLedgerAccount_SKEY"
      },
      {
        "name": "44396c8c-5e30-44e3-b61a-5d025701b727",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_TgkDepartment_SKEY",
        "toTable": "Tagetik Department",
        "toColumn": "DIM_TgkDepartment_SKEY"
      },
      {
        "name": "e3f8e182-3349-4f05-9383-d67af06d6ab4",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "Period",
        "toTable": "Period",
        "toColumn": "Period"
      },
      {
        "name": "d4fa46e6-2161-49d1-a36e-33fa5c4325e6",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_Date_Period_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY"
      },
      {
        "name": "4a0211d6-38a1-4827-904d-d49dade1e2ae",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_CostCenter_SKEY",
        "toTable": "Cost Center",
        "toColumn": "DIM_CostCenter_SKEY"
      },
      {
        "name": "2b0c9b7b-43ce-4172-acb4-fa1f92b76152",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_LedgerAccount_SKEY",
        "toTable": "Ledger Account",
        "toColumn": "DIM_LedgerAccount_SKEY"
      },
      {
        "name": "a4d2b156-b655-4bff-b232-dd673f4abd00",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_Plant_SKEY",
        "toTable": "Plant",
        "toColumn": "DIM_Plant_SKEY"
      },
      {
        "name": "e16c965e-db81-4316-b1fc-1ed0a2e09e19",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_TgkPlant_SKEY",
        "toTable": "Tagetik Plant",
        "toColumn": "DIM_TgkPlant_SKEY"
      },
      {
        "name": "3720151e-7bd4-40d9-9e01-9cd6c279e9d5",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_LegalEntity_SKEY",
        "toTable": "Legal Entity",
        "toColumn": "DIM_LegalEntity_SKEY"
      },
      {
        "name": "f9cd8fb5-56b9-4577-8d58-3c65ac11ea03",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_TgkLegalEntity_SKEY",
        "toTable": "Tagetik Legal Entity",
        "toColumn": "DIM_TgkLegalEntity_SKEY"
      },
      {
        "name": "cab6ae00-6a78-4e32-8f31-578591ba572f",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_CounterParty_SKEY",
        "toTable": "Counter Party",
        "toColumn": "DIM_CounterParty_SKEY"
      },
      {
        "name": "6122f7db-38b5-4bd0-adec-10dd26e9c483",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_GroupTgkLedgerAccount_SKEY",
        "toTable": "Group Tgk Ledger Account",
        "toColumn": "DIM_GroupTgkLedgerAccount_SKEY"
      },
      {
        "name": "28f4532b-c623-40b9-ba2e-628b441a7cd1",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY",
        "toTable": "Group Tgk Ledger Account Hierarchy",
        "toColumn": "DIM_GroupTgkLedgerAccountHierarchy_SKEY"
      },
      {
        "name": "9bab84a1-33aa-4fd9-88a4-d37367b7605a",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_GroupTgkDepartment_SKEY",
        "toTable": "Group Tgk Department",
        "toColumn": "DIM_GroupDepartmentAccount_SKEY"
      },
      {
        "name": "07572474-9e8e-4fa7-8f38-6afa1b813441",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY",
        "toTable": "Group Tgk Department Hierarchy",
        "toColumn": "DIM_GroupTgkDepartmentHierarchy_SKEY"
      },
      {
        "name": "a3451d44-2dfc-4c9b-99f5-ede716ac3cc0",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_AccountingCurrency_SKEY",
        "toTable": "Accounting Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "f2a9a397-f1b5-4eec-bf07-989740ad77ab",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "DIM_RegionalCurrency_SKEY",
        "toTable": "Regional Currency",
        "toColumn": "DIM_Currency_SKEY"
      },
      {
        "name": "46610f89-9e38-47ae-bc11-ebf1866144c7",
        "fromTable": "Reporting Bridge",
        "fromColumn": "GroupTgkLedgerAccountHashKey",
        "toTable": "Tagetik Ledger Account Reporting",
        "toColumn": "GroupTgkLedgerAccountHashKey"
      },
      {
        "name": "74358e85-9aee-4f47-8421-d30a74c81a20",
        "fromTable": "Ledger Period Balance",
        "fromColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "toTable": "Tagetik Ledger Account Department",
        "toColumn": "TgkLedgerAccountTgkDepartmentHashKey"
      },
      {
        "name": "ef7034ea-1ff8-47f0-bb69-b63fbc7be2fd",
        "fromTable": "Reporting Bridge",
        "fromColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "toTable": "Tagetik Ledger Account Department",
        "toColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "41919286-6904-4596-b3f4-7e31cceaefaf",
        "fromTable": "Ledger Actuals",
        "fromColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "toTable": "Tagetik Ledger Account Department",
        "toColumn": "TgkLedgerAccountTgkDepartmentHashKey"
      },
      {
        "name": "dd960dd0-b601-47fb-a410-94422738cdb8",
        "fromTable": "Tagetik Ledger Forecast",
        "fromColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "toTable": "Tagetik Ledger Account Department",
        "toColumn": "TgkLedgerAccountTgkDepartmentHashKey"
      },
      {
        "name": "3a799ff1-95a8-490d-9665-9c07ba6deab1",
        "fromTable": "Tagetik Ledger Budget",
        "fromColumn": "TgkLedgerAccountTgkDepartmentHashKey",
        "toTable": "Tagetik Ledger Account Department",
        "toColumn": "TgkLedgerAccountTgkDepartmentHashKey"
      },
      {
        "name": "4e71ad47-5264-44d9-a41d-2641061923b9",
        "fromTable": "Date Range",
        "fromColumn": "DIM_Date_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "37897386-fec5-41fc-9018-ddbf89dc209a",
        "fromTable": "Date Range Bis",
        "fromColumn": "DIM_Date_SKEY",
        "toTable": "Date",
        "toColumn": "DIM_Date_SKEY",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "b3d7fa08-693e-4f27-ba90-9ee802174022",
        "fromTable": "Ledger Actuals",
        "fromColumn": "Period",
        "toTable": "Period",
        "toColumn": "Period"
      }
    ],
    "roles": [
      {
        "name": "MEXBI",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "ribarra@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "sgonzalez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "gvillarreal@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "rcantu@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ileyva@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "asobrevilla@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jduran@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "pmartinez@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "jcaballero@gmp.com.mx",
            "identityProvider": "AzureAD"
          }
        ],
        "tablePermissions": [
          {
            "name": "Cost Center",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Ledger Account",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Ledger Actuals",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" "
          },
          {
            "name": "Ledger Period Balance",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" "
          },
          {
            "name": "Legal Entity",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Plant",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Data Forest",
            "filterExpression": "[Data Forest Id]=\"20_103\" "
          },
          {
            "name": "Accounting Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Regional Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Counter Party",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_103\" || [DIM_DataForest_SKEY]=BLANK()"
          }
        ]
      },
      {
        "name": "NAMBI",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Cost Center",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Ledger Account",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Ledger Actuals",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" "
          },
          {
            "name": "Ledger Period Balance",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" "
          },
          {
            "name": "Legal Entity",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Plant",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Data Forest",
            "filterExpression": "[Data Forest Id]=\"20_104\" "
          },
          {
            "name": "Accounting Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Regional Currency",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          },
          {
            "name": "Counter Party",
            "filterExpression": "[DIM_DataForest_SKEY]=\"20_104\" || [DIM_DataForest_SKEY]=BLANK()"
          }
        ]
      },
      {
        "name": "ALLBI",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "Benny.Loix@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Toon.Augustyns@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne.Van.Loy@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne.Bouter@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Hugo.Vandormael@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Kurt.Decat@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Jan.Steukers@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Frank.Kellens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Ralf.Loyen@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ddan-crisan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "raloy@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "cjones@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "dataservice@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Anne-Marie.Snepvangers@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Saar.Gillis@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Dominique.Dhaenens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Geert.Goijens@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RSomayajula@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RStegmeier@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CKemmerer@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "BSkelly@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PGamma@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MDeMasi@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MIdrees@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "SWimalasooriya@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JCorera@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "CGoodwin@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RSpear@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "AGopalakrishnan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "DFagan@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "edilson.santos@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "FHilmy@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PRajagopal@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ZBaloch@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "AEich@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JKilbane@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "PPhillips@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "swestmoreland@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Yannick.Verthongen@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "JLorenzoni@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "SJha@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "miriam.vencken@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "yvan.hoefman@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "MSmerekanicz@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "DPetersen@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Nele.Van.Peteghem@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "RBlanc@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "GMullet@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Sophie.Chevallier@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Wim.Vanpeel@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Spreston@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "igarza@gmp.com.mx",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Moskam@unimin.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Eduardo.Sainz@sibelco.com",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "Matthew.Lewtas@sibelco.com",
            "identityProvider": "AzureAD"
          }
        ]
      }
    ]
  }
}